import type { Achievement } from './achievements';

export type AchievementStory = Readonly<{ en: string; es: string }>;

const stories: Record<string, AchievementStory> = {
  'first-thread': { en: 'One tug was enough to wake a kitten. It inspected the thread, sat on it, and declared itself essential to the project.', es: 'Un tirón bastó para despertar a un gatito. Inspeccionó el hilo, se sentó encima y se declaró imprescindible para el proyecto.' },
  'persistent-paws': { en: 'After 75 pulls, a cat brought you a snack. It ate the snack on the way, but the moral support was genuine.', es: 'Tras 75 tirones, un gato te trajo una merienda. Se la comió por el camino, pero el apoyo moral era sincero.' },
  'paw-marathon': { en: 'Five hundred pulls! The feline coach awarded you a medal, then chased its ribbon. Your sporting career is now under the sofa.', es: '¡Quinientos tirones! El entrenador felino te dio una medalla y luego persiguió la cinta. Tu carrera deportiva está bajo el sofá.' },
  'thread-legend': { en: 'After 2,500 pulls, kittens whisper your legend at bedtime. The oldest cat insists it taught you everything. It was asleep that day.', es: 'Tras 2.500 tirones, los gatitos cuentan tu leyenda antes de dormir. El gato mayor dice que te enseñó todo. Ese día estaba dormido.' },
  'first-skein': { en: 'Your first thousand yarn became a respectable little pile. A kitten immediately flattened it into a bed. Quality control passed.', es: 'Tus primeras mil unidades de lana formaron una pila respetable. Un gatito la convirtió en cama. Control de calidad superado.' },
  'woolly-ambition': { en: 'Ten thousand yarn, and someone suggested a bigger storeroom. The cats voted for a bigger sunbeam. Negotiations continue.', es: 'Diez mil de lana y alguien propuso ampliar el almacén. Los gatos votaron por un rayo de sol más grande. Siguen las negociaciones.' },
  'thread-empire': { en: 'At a hundred thousand yarn, the cats declared an empire. Its border is a cardboard box. Its emperor is licking a paw.', es: 'Con cien mil de lana, los gatos declararon un imperio. Su frontera es una caja de cartón. Su emperador se está lamiendo una pata.' },
  'million-meows': { en: 'A million yarn deserved a grand speech. The forecat stepped up, meowed once, and requested dinner. Not a dry whisker in the room.', es: 'Un millón de lana merecía un gran discurso. La jefa subió, maulló una vez y pidió la cena. No quedó un bigote sin emocionarse.' },
  'cosmic-skein': { en: 'A billion yarn could reach the stars, said a kitten. Everyone nodded wisely. Nobody volunteered to untangle the first meter.', es: 'Mil millones de lana llegarían a las estrellas, dijo un gatito. Todos asintieron muy serios. Nadie quiso desenredar el primer metro.' },
  'first-hire': { en: 'Your first employee arrived with soft paws and no references. It fell asleep during orientation. You hired it anyway, obviously.', es: 'Tu primer empleado llegó con patas suaves y sin referencias. Se durmió durante la bienvenida. Lo contrataste igual, por supuesto.' },
  'cat-party': { en: 'Ten cats formed a very small union. Their first demand was a shared nap. Their second was not actually sharing the best cushion.', es: 'Diez gatos formaron un sindicato diminuto. Primero pidieron una siesta compartida. Después, no compartir el mejor cojín.' },
  'crowded-sofa': { en: 'A hundred cats fit on the sofa, somehow. You were offered a generous corner of the floor. Someone even warmed it for you.', es: 'Cien gatos caben en el sofá, de alguna manera. Te ofrecieron un generoso rincón del suelo. Alguien incluso te lo calentó.' },
  'fluffy-thousand': { en: 'A thousand cats answered the morning roll call. Unfortunately, they all answered to the sound of the same treat bag.', es: 'Mil gatos respondieron al pasar lista por la mañana. Por desgracia, todos respondían al sonido de la misma bolsa de premios.' },
  'cat-city': { en: 'A hundred thousand cats needed a mayor. They elected the one sleeping on the paperwork. Finally, a leader who understands them.', es: 'Cien mil gatos necesitaban alcalde. Eligieron al que dormía sobre los documentos. Por fin, alguien que los entiende.' },
  'mixed-company': { en: 'Three crews met to divide the work. Each took a different task and the same lunch break. A promising start to collaboration.', es: 'Tres equipos se reunieron para repartir el trabajo. Cada uno eligió una tarea distinta y la misma pausa para comer. Buen comienzo.' },
  'full-house': { en: 'Five crews now have their own specialties. The box inspection department remains suspiciously overstaffed, but morale is excellent.', es: 'Cinco equipos ya tienen especialidad propia. El departamento de inspección de cajas tiene demasiado personal, pero todos están felices.' },
  'ten-lives': { en: 'All ten crews gathered for a portrait. Three faced the camera, six faced a moth, and one became the photographer by sitting on it.', es: 'Los diez equipos posaron para una foto. Tres miraban a cámara, seis a una polilla y uno se hizo fotógrafo sentándose sobre ella.' },
  'first-upgrade': { en: 'The first improvement was approved with a pawprint. The committee then napped on the plans, keeping your bright idea pleasantly warm.', es: 'La primera mejora se aprobó con una huella. El comité durmió sobre los planos para mantener tu gran idea bien calentita.' },
  'toolbox': { en: 'Three improvements later, the toolbox finally opened. Inside was a kitten. It claimed to be the most important tool, and had a point.', es: 'Tras tres mejoras, la caja de herramientas se abrió. Dentro había un gatito. Afirmó ser la herramienta más importante. No le faltaba razón.' },
  'serial-tinkerer': { en: 'Ten improvements made the workshop wonderfully efficient. The supervisor now completes its daily inspection without leaving the cushion.', es: 'Diez mejoras hicieron el taller muy eficiente. El supervisor ya puede completar su inspección diaria sin abandonar el cojín.' },
  'professor-purr': { en: 'Twenty-five improvements earned you a tiny academic cap. A cat stole the tassel before graduation. Your research has practical value.', es: 'Veinticinco mejoras te dieron un pequeño birrete. Un gato robó la borla antes de graduarte. Tu investigación tiene aplicaciones prácticas.' },
  'fresh-start': { en: 'You opened a fresh chapter. A kitten brought its favorite thread from the old one, just in case starting over needed a little comfort.', es: 'Abriste un capítulo nuevo. Un gatito trajo su hilo favorito del anterior, por si empezar de nuevo necesitaba un poco de cariño.' },
  'third-time': { en: 'On the third restart, the cats knew the routine. They unpacked the cushions first. Apparently, everything else counts as optional.', es: 'Al tercer reinicio, los gatos ya conocían la rutina. Desembalaron primero los cojines. Al parecer, todo lo demás es opcional.' },
  'nine-lives': { en: 'Nine restarts, and the oldest cat still calls this a trial run. It has kept every welcome mat. Sentimentality takes up a lot of space.', es: 'Nueve reinicios y el gato mayor aún dice que esto es una prueba. Ha guardado todos los felpudos. El cariño ocupa bastante espacio.' },
  'divine-favor': { en: 'Your first blessing arrived in a warm beam of light. A kitten promptly lay in it. Divine power has never been put to better use.', es: 'Tu primera bendición llegó en un rayo de luz tibio. Un gatito se tumbó encima. Nunca se había aprovechado tan bien el poder divino.' },
  demigod: { en: 'Two blessings made the cats feel half divine. The other half still gets startled by cucumbers. Olympus has agreed not to mention it.', es: 'Dos bendiciones hicieron a los gatos sentirse semidioses. La otra mitad aún se asusta con los pepinos. El Olimpo prometió discreción.' },
  pantheon: { en: 'All twelve gods blessed the workshop, then tried to share one sunny step. Even eternal wisdom cannot solve the cushion problem.', es: 'Los doce dioses bendijeron el taller y trataron de compartir un escalón soleado. Ni la sabiduría eterna resuelve el problema del cojín.' },
  'hello-friend': { en: 'Your first companion settled beside you without asking. It was not being rude. It simply knew you had been saving that spot.', es: 'Tu primer acompañante se acomodó a tu lado sin preguntar. No era mala educación. Simplemente sabía que le estabas guardando ese sitio.' },
  'friend-circle': { en: 'Three friends decided to keep you company. One watched the yarn, one watched you, and one watched the other two doing all the work.', es: 'Tres amigos decidieron acompañarte. Uno vigilaba la lana, otro te vigilaba a ti y el tercero vigilaba cómo trabajaban los otros dos.' },
  'whole-family': { en: 'All six companions gathered for a family photo. Biscuit tripped over the yarn. Everyone leaned in to help, and that became the photo.', es: 'Los seis acompañantes posaron para la foto familiar. Biscuit tropezó con la lana. Todos se acercaron a ayudar y esa fue la foto.' },
  'new-look': { en: 'The new companion inherited the cushion and a very serious handover note. It read: warm side on the left. Please maintain standards.', es: 'El nuevo acompañante heredó el cojín y una nota muy seria: el lado caliente está a la izquierda. Por favor, mantén el nivel.' },
  'while-you-napped': { en: 'You returned to a thousand yarn and a sleeping crew. They insist they worked the entire time. One has a thread stuck to its whiskers.', es: 'Volviste y encontraste mil de lana y al equipo dormido. Insisten en que trabajaron todo el tiempo. Uno tiene un hilo pegado al bigote.' },
  'dream-shift': { en: 'The night shift left a hundred thousand yarn and a note: nothing happened. The overturned basket has politely declined to comment.', es: 'El turno nocturno dejó cien mil de lana y una nota: no pasó nada. La cesta volcada ha preferido no hacer declaraciones.' },
  'cozy-hour': { en: 'After an hour together, a cat quietly moved its nap closer to you. No ceremony, no speech. Just the highest possible feline review.', es: 'Tras una hora juntos, un gato acercó su siesta a ti. Sin ceremonia ni discurso. Solo la mejor reseña que puede dar un felino.' },
  'group-hug': { en: 'Ten new workers arrived together and attempted a group hug. It became a pile of tails. Nobody wants to fix it yet.', es: 'Diez trabajadores llegaron juntos e intentaron darse un abrazo. Se convirtió en una montaña de colas. Nadie quiere arreglarla todavía.' },
  'all-in': { en: 'You hired every cat you could afford. The accountant fainted softly into a basket. Luckily, the new team includes excellent purr support.', es: 'Contrataste todos los gatos que podías pagar. El contable se desmayó suavemente en una cesta. Por suerte, el equipo ofrece apoyo con ronroneos.' },
};

export function achievementStory(id: Achievement['id'] | string, language: 'en' | 'es'): string {
  const story = stories[id];
  return story ? story[language] : '';
}
