import type { Achievement } from './achievements';

export type AchievementStory = Readonly<{ en: string; es: string }>;

const stories: Record<string, AchievementStory> = {
  'first-thread': { en: 'You gave the first thread one brave tug, and the workshop went silent. A kitten inspected the result, circled it twice, then sat directly on the evidence. Congratulations: you built a production line with a furry embargo.', es: 'Le diste un tirón valiente al primer hilo y el taller quedó en silencio. Un gatito inspeccionó el resultado, dio dos vueltas y se sentó sobre la prueba. Felicitaciones: armaste una línea de producción con embargo peludo.' },
  'persistent-paws': { en: 'Seventy-five pulls later, a cat arrived to celebrate your stamina with a snack. It sampled the snack for quality, then sampled it again for science. The support was heartfelt; the snack has been promoted to folklore.', es: 'Setenta y cinco tirones después, un gato llegó a celebrar tu constancia con una merienda. La probó por control de calidad y la volvió a probar por ciencia. El apoyo fue sincero; la merienda ya es leyenda.' },
  'paw-marathon': { en: 'Five hundred pulls earned you a medal from the feline athletics committee. The presenter spotted the ribbon, chased it under the sofa, and never returned. Your sporting legacy is now hiding behind a dust bunny.', es: 'Quinientos tirones te ganaron una medalla del comité felino de atletismo. Quien la entregaba vio la cinta, la persiguió bajo el sofá y no volvió. Tu legado deportivo ahora se esconde detrás de una pelusa.' },
  'thread-legend': { en: 'After 2,500 pulls, kittens whisper your name before bedtime like a heroic yarn ballad. The oldest cat claims it trained you from day one. It slept through day one, but history is written by whoever owns the lap.', es: 'Tras 2.500 tirones, los gatitos susurran tu nombre antes de dormir como una balada de lana. El gato mayor asegura que te entrenó desde el primer día. Se durmió ese día, pero la historia la escribe quien ocupa el regazo.' },
  'first-skein': { en: 'Your first thousand yarn made a tidy, respectable pile. A kitten tested its firmness, kneaded it twice, and converted it into premium bedding. Inventory says one thousand; management says one extremely fancy mattress.', es: 'Tus primeras mil unidades de lana hicieron una pila ordenada y respetable. Un gatito comprobó la firmeza, amasó dos veces y la convirtió en cama premium. Inventario dice mil; gerencia dice un colchón muy elegante.' },
  'woolly-ambition': { en: 'Ten thousand yarn triggered a meeting about expanding the storeroom. The cats voted unanimously for enlarging the nearest sunbeam instead. The proposal passed, because nobody can argue with a quorum that is purring.', es: 'Diez mil de lana dispararon una reunión para ampliar el depósito. Los gatos votaron por agrandar el rayo de sol más cercano. La propuesta salió aprobada, porque nadie discute con un quórum que ronronea.' },
  'thread-empire': { en: 'At one hundred thousand yarn, the cats declared a glorious empire. Its borders are a cardboard box, its treasury is three buttons, and its emperor is licking a paw. Imperial stability has never looked so washable.', es: 'Con cien mil de lana, los gatos declararon un imperio glorioso. Sus fronteras son una caja de cartón, su tesoro tres botones y su emperador se lame una pata. La estabilidad imperial nunca fue tan lavable.' },
  'million-meows': { en: 'A million yarn deserved trumpets, banners, and a speech from the forecat. It climbed the crate, meowed once, and demanded dinner with remarkable dignity. Not a dry whisker remained after that budget presentation.', es: 'Un millón de lana merecía trompetas, banderas y un discurso de la jefa. Subió a una caja, maulló una vez y exigió la cena con gran dignidad. No quedó un bigote seco tras esa presentación de presupuesto.' },
  'cosmic-skein': { en: 'A billion yarn could reach the stars, announced a kitten staring at the ceiling. Everyone nodded until someone mentioned untangling the first meter. The space program is delayed pending a nap and a miracle.', es: 'Mil millones de lana podrían llegar a las estrellas, anunció un gatito mirando el techo. Todos asintieron hasta que alguien mencionó desenredar el primer metro. El programa espacial se demora por siesta y milagro.' },
  'first-hire': { en: 'Your first employee arrived with soft paws, a blank résumé, and enormous confidence. It fell asleep during orientation, woke up for lunch, and accepted the role. Apparently the interview was for you.', es: 'Tu primer empleado llegó con patas suaves, currículum vacío y enorme confianza. Se durmió en la bienvenida, despertó para almorzar y aceptó el puesto. Al parecer, la entrevista era para ti.' },
  'cat-party': { en: 'Ten cats formed a tiny union before you could find enough bowls. Their first demand was a shared nap, their second was exclusive rights to the best cushion. Negotiations ended when everyone fell asleep at the table.', es: 'Diez gatos formaron un sindicato diminuto antes de que encontraras suficientes platos. Primero pidieron una siesta compartida y luego derechos exclusivos sobre el mejor cojín. La negociación terminó cuando todos se durmieron en la mesa.' },
  'crowded-sofa': { en: 'A hundred cats somehow fit on the sofa, in defiance of geometry and basic manners. They offered you a generous corner of the floor, already warmed by someone else. Hospitality is alive, if slightly fur-covered.', es: 'Cien gatos entraron en el sofá, desafiando la geometría y los modales básicos. Te ofrecieron un rincón generoso del piso, ya calentito por alguien más. La hospitalidad sigue viva, aunque con bastante pelo.' },
  'fluffy-thousand': { en: 'A thousand cats answered the morning roll call at exactly the sound of one treat bag opening. Names were abandoned, attendance was perfect, and the supervisor vanished beneath tails. Administration has become a snack-based religion.', es: 'Mil gatos respondieron al pase de lista justo al sonido de una bolsa de premios. Los nombres dejaron de importar, la asistencia fue perfecta y la supervisora desapareció entre colas. La administración ahora es una religión de snacks.' },
  'cat-city': { en: 'One hundred thousand cats needed a mayor, a plan, and probably several traffic lights. They elected the cat sleeping on the paperwork without waking it. Finally, a leader who understands the city budget.', es: 'Cien mil gatos necesitaban alcalde, plan y probablemente varios semáforos. Eligieron al gato que dormía sobre los papeles sin despertarlo. Por fin, un líder que entiende el presupuesto de la ciudad.' },
  'mixed-company': { en: 'Three crews met to divide the work with charts, schedules, and serious nods. Each chose a different task and the exact same lunch break. Collaboration is thriving, provided lunch lasts forever.', es: 'Tres equipos se reunieron para repartir el trabajo con gráficos, horarios y gestos serios. Cada uno eligió una tarea distinta y exactamente la misma pausa para comer. La colaboración prospera, mientras el almuerzo sea eterno.' },
  'full-house': { en: 'Five crews now have specialties, badges, and opinions about their workflow. The box-inspection department is suspiciously overstaffed, yet reports flawless morale. Some mysteries are best left unopened, like boxes.', es: 'Cinco equipos ya tienen especialidades, insignias y opiniones sobre su método. El departamento de inspección de cajas tiene personal sospechosamente de más, pero reporta moral impecable. Hay misterios que conviene no abrir, como las cajas.' },
  'ten-lives': { en: 'All ten crews gathered for a grand portrait to celebrate the operation. Three faced the camera, six chased a moth, and one sat on the shutter button. The official photo is now mostly tail.', es: 'Los diez equipos se juntaron para un gran retrato de celebración. Tres miraron a cámara, seis persiguieron una polilla y uno se sentó sobre el disparador. La foto oficial ahora es casi toda cola.' },
  'first-upgrade': { en: 'The first improvement received a ceremonial pawprint and a standing purr. Then the committee napped on the plans to keep your idea warm. Innovation is alive, but it has claimed the blueprint as a blanket.', es: 'La primera mejora recibió una huella ceremonial y un ronroneo de pie. Después, el comité durmió sobre los planos para mantener tu idea calentita. La innovación vive, pero reclamó el plano como manta.' },
  'toolbox': { en: 'Three upgrades later, the toolbox finally opened with a dramatic creak. Inside sat a kitten wearing a measuring tape like a crown. It is now the most important tool, and it refuses to be calibrated.', es: 'Tres mejoras después, la caja de herramientas se abrió con un crujido dramático. Dentro había un gatito con una cinta métrica como corona. Ahora es la herramienta más importante y se niega a calibrarse.' },
  'serial-tinkerer': { en: 'Ten upgrades made the workshop faster, smarter, and suspiciously more comfortable. The supervisor completes every inspection without leaving its cushion. Efficiency has reached its final form: delegation with whiskers.', es: 'Diez mejoras hicieron el taller más rápido, listo y sospechosamente cómodo. La supervisora completa cada inspección sin abandonar su cojín. La eficiencia llegó a su forma final: delegar con bigotes.' },
  'professor-purr': { en: 'Twenty-five improvements earned you a tiny academic cap and a solemn graduation ceremony. A cat stole the tassel before the applause began. Your research has passed peer review and failed cat review.', es: 'Veinticinco mejoras te ganaron un birrete diminuto y una graduación solemne. Un gato robó la borla antes de los aplausos. Tu investigación aprobó la revisión de pares y desaprobó la revisión felina.' },
  'fresh-start': { en: 'You opened a fresh chapter with clean floors, bold hopes, and absolutely no old yarn. A kitten quietly carried in its favorite thread from the previous run. Starting over is permitted; sentimental contraband is mandatory.', es: 'Abriste un capítulo nuevo con pisos limpios, grandes esperanzas y nada de lana vieja. Un gatito trajo en secreto su hilo favorito de la partida anterior. Empezar de nuevo está permitido; el contrabando sentimental es obligatorio.' },
  'third-time': { en: 'By the third restart, the cats knew the procedure better than the manual did. They unpacked the cushions first and watched you handle the boring parts. Apparently, everything else is optional infrastructure.', es: 'Al tercer reinicio, los gatos conocían el procedimiento mejor que el manual. Desembalaron primero los cojines y te miraron hacer las partes aburridas. Al parecer, todo lo demás es infraestructura opcional.' },
  'nine-lives': { en: 'Nine restarts later, the oldest cat still calls this a trial run with a straight face. It has saved every welcome mat and labeled them by era. Nostalgia is just hoarding with better branding.', es: 'Nueve reinicios después, el gato mayor todavía llama a esto una prueba sin inmutarse. Guardó todos los felpudos y los etiquetó por época. La nostalgia es acumular cosas con mejor publicidad.' },
  'divine-favor': { en: 'Your first blessing arrived in a warm beam of light, complete with heavenly sparkles. A kitten stepped into it, turned around once, and occupied the miracle. Divine power has been converted into a nap permit.', es: 'Tu primera bendición llegó en un rayo tibio, con destellos celestiales incluidos. Un gatito entró, dio una vuelta y ocupó el milagro. El poder divino fue convertido en permiso para siesta.' },
  demigod: { en: 'Two blessings made the cats feel half divine and entirely unbearable. The other half still jumps at cucumbers and loses arguments with vacuum cleaners. Olympus has requested that nobody mention this at dinner.', es: 'Dos bendiciones hicieron que los gatos se sintieran semidioses e insoportables por completo. La otra mitad todavía salta ante pepinos y pierde discusiones con aspiradoras. El Olimpo pidió que nadie lo mencione en la cena.' },
  pantheon: { en: 'All twelve gods blessed the workshop with thunder, wisdom, and excellent lighting. Then they tried to share one sunny step and began a silent cushion war. Eternity is long; apparently it is not long enough for turn-taking.', es: 'Los doce dioses bendijeron el taller con truenos, sabiduría y luz excelente. Después quisieron compartir un escalón soleado y empezó una guerra silenciosa por el cojín. La eternidad es larga, pero no alcanza para turnarse.' },
  'hello-friend': { en: 'Your first companion settled beside you without asking, watching every tug like a tiny foreman. It was not rude; it simply recognized its reserved seat. Friendship begins when your chair loses a vote.', es: 'Tu primer compañero se acomodó a tu lado sin preguntar y vigiló cada tirón como un capataz diminuto. No fue mala educación: reconoció su asiento reservado. La amistad empieza cuando tu silla pierde una votación.' },
  'friend-circle': { en: 'Three friends decided to keep you company around the yarn pile. One watched the yarn, one watched you, and one watched the other two avoiding work. Teamwork is mostly surveillance with better fur.', es: 'Tres amigos decidieron hacerte compañía junto a la pila de lana. Uno vigiló la lana, otro te vigiló a ti y el tercero vigiló a los otros dos evitando trabajar. El trabajo en equipo es vigilancia con mejor pelo.' },
  'whole-family': { en: 'All six companions posed for a family portrait after much bribery with treats. Biscuit tripped over the yarn, everyone rushed in to help, and the camera clicked. The perfect photo is six tails and one emergency.', es: 'Los seis compañeros posaron para la foto familiar tras muchos premios. Biscuit tropezó con la lana, todos corrieron a ayudar y la cámara hizo clic. La foto perfecta son seis colas y una emergencia.' },
  'new-look': { en: 'The new companion inherited a cushion and a very serious handover note. It read: warm side on the left, snacks at four, no compromises. The newcomer signed it by sitting on the pen.', es: 'El nuevo compañero heredó un cojín y una nota de traspaso muy seria. Decía: lado cálido a la izquierda, premios a las cuatro y cero concesiones. El recién llegado la firmó sentándose sobre el bolígrafo.' },
  'while-you-napped': { en: 'You returned from a nap to one thousand yarn and a crew pretending not to snore. They insist they worked continuously and present one thread stuck to a whisker as proof. The audit has been purr-approved.', es: 'Volviste de una siesta con mil de lana y un equipo fingiendo no roncar. Insisten en que trabajaron sin parar y muestran un hilo pegado a un bigote como prueba. La auditoría fue aprobada con ronroneos.' },
  'dream-shift': { en: 'The night shift left one hundred thousand yarn and a note saying nothing unusual happened. The overturned basket, loose buttons, and guilty-looking cat declined comment. The report is flawless because the witnesses are asleep.', es: 'El turno nocturno dejó cien mil de lana y una nota diciendo que no pasó nada raro. La cesta volcada, los botones sueltos y un gato culpable no comentaron. El informe es impecable porque los testigos duermen.' },
  'cozy-hour': { en: 'After an hour together, a cat quietly moved its nap closer to you. No ceremony, no speech, just a slow shuffle into shared warmth. You have received the highest feline review: tolerated proximity.', es: 'Tras una hora juntos, un gato acercó su siesta hacia ti. Sin ceremonia ni discurso, solo un movimiento lento hacia el calor compartido. Recibiste la máxima reseña felina: proximidad tolerada.' },
  'group-hug': { en: 'Ten new workers arrived at once and attempted a welcoming group hug. It became a knot of tails, paws, and confused purring near the doorway. Nobody will fix it because the pile has elected itself furniture.', es: 'Diez trabajadores nuevos llegaron juntos e intentaron un abrazo de bienvenida. Se volvió un nudo de colas, patas y ronroneos confundidos junto a la puerta. Nadie lo arreglará porque la pila se eligió mueble.' },
  'all-in': { en: 'You hired every cat you could afford, and the accountant fainted gently into a basket. The new team surrounded them with purrs and one unpaid invoice. Financial planning is now a collective nap initiative.', es: 'Contrataste todos los gatos que podías pagar y el contador se desmayó suavemente en una cesta. El equipo nuevo lo rodeó con ronroneos y una factura sin pagar. La planificación financiera ahora es una siesta colectiva.' },
};

export function achievementStory(id: Achievement['id'] | string, language: 'en' | 'es'): string {
  const story = stories[id];
  return story ? story[language] : '';
}
