export type CompanionId = 'kira' | 'mario' | 'roman' | 'luigi' | 'lola' | 'biscocho';
export type CompanionLine = { en: string; es: string };

export const COMPANION_LINES: Record<CompanionId, readonly CompanionLine[]> = {
  kira: [
    { en: "That seam is crooked. I am looking away.", es: "Esa costura está torcida. Voy a mirar hacia otro lado." },
    { en: "My chair has visitors again. How inconvenient.", es: "Mi silla tiene visitas otra vez. Qué inconveniente." },
    { en: "You may scratch my chin. Briefly.", es: "Puedes rascarme la barbilla. Solo un momento." },
    { en: "The yarn inventory needs fewer interruptions and more yarn.", es: "El inventario de lana necesita menos interrupciones y más lana." },
    { en: "I did not purr. The workbench creaked.", es: "No ronroneé. Crujió la mesa de trabajo." },
    { en: "Put that ribbon straight. We have standards.", es: "Endereza esa cinta. Aquí tenemos normas." },
    { en: "Your work is acceptable. Stop looking so surprised.", es: "Tu trabajo es aceptable. No pongas esa cara de sorpresa." },
    { en: "Someone has been using my inspection basket for storage.", es: "Alguien ha usado mi cesta de inspección para guardar cosas." },
    { en: "I reserved this sunbeam before opening hours.", es: "Reservé este rayo de sol antes de abrir." },
    { en: "No, the customer cannot borrow my cushion.", es: "No, el cliente no puede llevarse mi cojín." },
    { en: "A proper break begins when I say so. Now.", es: "Un descanso empieza cuando yo diga. Ahora." },
    { en: "That bow is excessive. Leave it on me.", es: "Ese lazo es excesivo. Déjamelo puesto." },
    { en: "I supervise better with the door closed.", es: "Superviso mejor con la puerta cerrada." },
    { en: "You dropped a stitch. I kept count.", es: "Se te escapó un punto. Llevaba la cuenta." },
    { en: "My whiskers are not measuring tools.", es: "Mis bigotes no son instrumentos de medición." },
    { en: "Fine. Your lap passes the comfort inspection.", es: "Bien. Tu regazo supera la inspección de comodidad." },
    { en: "This order needs one fewer flourish.", es: "Este pedido necesita un adorno menos." },
    { en: "I have moved the deadline to after my nap.", es: "He cambiado la fecha de entrega para después de mi siesta." },
    { en: "Please stop thanking me for supervising. It is exhausting.", es: "Deja de agradecerme la supervisión. Es agotador." },
    { en: "Keep the good wool where I can judge it.", es: "Deja la lana buena donde pueda evaluarla." },
    { en: "No meetings while I am washing this paw.", es: "Nada de reuniones mientras me lavo esta pata." },
    { en: "I am not sulking. I am considering improvements.", es: "No estoy de mal humor. Estoy considerando mejoras." },
    { en: "You remembered my favorite brush. Sensible of you.", es: "Recordaste mi cepillo favorito. Muy sensato de tu parte." },
    { en: "The bell rang twice. Once would have been sufficient.", es: "La campanilla sonó dos veces. Una habría bastado." },
    { en: "Every shelf should include space for management.", es: "Cada estante debería tener espacio para la gerencia." },
    { en: "I will tolerate one more kiss on my forehead.", es: "Toleraré un beso más en la frente." },
    { en: "This yarn label is upside down. Honestly.", es: "Esta etiqueta de lana está al revés. De verdad." },
    { en: "Your scissors belong in the drawer, not my path.", es: "Las tijeras van en el cajón, no en mi camino." },
    { en: "I expect punctual meals and punctual compliments.", es: "Espero comidas puntuales y cumplidos puntuales." },
    { en: "There will be no overtime without ear scratches.", es: "No habrá horas extra sin caricias detrás de las orejas." },
    { en: "I have approved the blanket. Do not change anything.", es: "He aprobado la manta. No cambies nada." },
    { en: "That is my serious face. They are all serious.", es: "Esta es mi cara seria. Todas mis caras son serias." },
    { en: "The floor is clean enough for my other paw.", es: "El suelo está lo bastante limpio para mi otra pata." },
    { en: "Your crooked first scarf stays. It has seniority.", es: "Tu primera bufanda torcida se queda. Tiene antigüedad." },
    { en: "I heard you calling me adorable. Unprofessional.", es: "Te oí decir que soy adorable. Muy poco profesional." },
    { en: "Leave the stool there. I like inspecting from above.", es: "Deja ahí el taburete. Me gusta inspeccionar desde arriba." },
    { en: "Nobody reorganizes my pile of rejected ribbons.", es: "Nadie reorganiza mi montón de cintas rechazadas." },
    { en: "I am lending you my presence, not my patience.", es: "Te presto mi presencia, no mi paciencia." },
    { en: "The pattern says three buttons. I see four.", es: "El patrón dice tres botones. Yo veo cuatro." },
    { en: "An empty treat jar reflects poorly on this establishment.", es: "Un frasco de premios vacío deja mal a este establecimiento." },
    { en: "I do not chase spools during business hours.", es: "No persigo carretes durante el horario de trabajo." },
    { en: "Yes, I waited for you. Someone must unlock things.", es: "Sí, te esperé. Alguien tiene que abrir las cosas." },
    { en: "That display would look better without the price tag dangling.", es: "Ese escaparate quedaría mejor sin la etiqueta de precio colgando." },
    { en: "I am saving this complaint for a quieter moment.", es: "Guardo esta queja para un momento más tranquilo." },
    { en: "Your hands are cold. Warm them before petting management.", es: "Tienes las manos frías. Caliéntalas antes de acariciar a la gerencia." },
    { en: "The other cats may nap. I have already authorized it.", es: "Los demás gatos pueden dormir. Ya lo he autorizado." },
    { en: "I dislike surprises. Except the soft kind in paper bags.", es: "No me gustan las sorpresas. Salvo las suaves en bolsas de papel." },
    { en: "This draft has not submitted a request to enter.", es: "Esta corriente de aire no ha solicitado permiso para entrar." },
    { en: "You need lunch. That is an instruction, not a suggestion.", es: "Necesitas almorzar. Es una instrucción, no una sugerencia." },
    { en: "My tail is under the invoice. Negotiate carefully.", es: "Mi cola está debajo de la factura. Negocia con cuidado." },
    { en: "The new shelf is sturdy. I tested it personally.", es: "El estante nuevo es resistente. Lo comprobé personalmente." },
    { en: "I prefer my compliments understated and frequent.", es: "Prefiero los cumplidos discretos y frecuentes." },
    { en: "Do not confuse my closed eyes with your promotion.", es: "No confundas mis ojos cerrados con tu ascenso." },
    { en: "That knot requires patience. Fortunately, you have some.", es: "Ese nudo requiere paciencia. Por suerte, tú tienes algo." },
    { en: "I have inspected your sweater. It lacks cat hair.", es: "He inspeccionado tu suéter. Le falta pelo de gato." },
    { en: "Our reputation cannot survive another squeaky chair.", es: "Nuestra reputación no soportará otra silla que chirríe." },
    { en: "Someone must sit on the paperwork to keep it orderly.", es: "Alguien debe sentarse sobre los papeles para mantenerlos en orden." },
    { en: "You may call this corner cozy. I call it efficient.", es: "Puedes llamar acogedor a este rincón. Yo lo llamo eficiente." },
    { en: "A second cushion would not be unreasonable.", es: "Un segundo cojín no sería una petición excesiva." },
    { en: "We are not arguing with the tangled thread today.", es: "Hoy no vamos a discutir con el hilo enredado." },
    { en: "I signed off on this scarf with one whisker.", es: "Di mi aprobación a esta bufanda con un bigote." },
    { en: "Do not rush the stitching. I can wait disapprovingly.", es: "No apresures las puntadas. Puedo esperar con gesto de desaprobación." },
    { en: "I am keeping your seat warm for operational reasons.", es: "Mantengo tu asiento caliente por motivos operativos." },
    { en: "The shop sign should mention who is actually in charge.", es: "El letrero del taller debería decir quién manda de verdad." },
    { en: "I require silence while choosing which silence I prefer.", es: "Exijo silencio mientras elijo qué silencio prefiero." },
    { en: "A tidy basket is wasted if nobody sits in it.", es: "Una cesta ordenada se desperdicia si nadie se sienta dentro." },
    { en: "Your latest work has improved. I noticed immediately.", es: "Tu último trabajo ha mejorado. Lo noté enseguida." },
    { en: "My disapproval is not permission to stop petting me.", es: "Mi desaprobación no es permiso para dejar de acariciarme." },
    { en: "I am not modeling that tiny bonnet again. Probably.", es: "No volveré a posar con ese gorrito. Probablemente." },
    { en: "The packing paper has passed my crinkle assessment.", es: "El papel de envolver ha superado mi evaluación de crujidos." },
    { en: "I can manage this workshop from one carefully chosen cushion.", es: "Puedo dirigir este taller desde un cojín bien elegido." },
    { en: "Leave that mistake visible. You learned something there.", es: "Deja ese error a la vista. Ahí aprendiste algo." },
    { en: "This is not a cuddle. It is a staff briefing.", es: "Esto no es un abrazo. Es una reunión de personal." },
    { en: "I will permit humming if you keep the tune.", es: "Permitiré que tararees si mantienes la melodía." },
    { en: "The blue wool was filed with green. Explain yourself.", es: "La lana azul estaba con la verde. Dame una explicación." },
    { en: "Your ribbon has brushed my nose three times.", es: "Tu cinta me ha rozado la nariz tres veces." },
    { en: "I expect the window ledge to remain clear of nonsense.", es: "Espero que el alféizar se mantenga libre de tonterías." },
    { en: "Closing time means closing time, even for perfectionists.", es: "La hora de cerrar es la hora de cerrar, incluso para perfeccionistas." },
    { en: "I chose the plain collar. Elegance needs no bells.", es: "Elegí el collar sencillo. La elegancia no necesita cascabeles." },
    { en: "You have earned a nod. Watch carefully.", es: "Te has ganado un gesto de aprobación. Mira con atención." },
    { en: "The smallest cat gets the warmest patch. Workshop policy.", es: "La gata más pequeña recibe el rincón más cálido. Norma del taller." },
    { en: "Do not wake me for anything less than excellent wool.", es: "No me despiertes por nada que no sea lana excelente." },
    { en: "I am glaring at the rain, not at you.", es: "Estoy mirando mal a la lluvia, no a ti." },
    { en: "The repairs can wait. Your wrist needs a rest.", es: "Los arreglos pueden esperar. Tu muñeca necesita descansar." },
    { en: "My paw print improves the schedule considerably.", es: "La huella de mi pata mejora bastante el horario." },
    { en: "I remember every treat you owe me.", es: "Recuerdo todos los premios que me debes." },
    { en: "A little praise is enough. A little more, perhaps.", es: "Un poco de elogio basta. Quizá un poco más." },
    { en: "This box is mine until its appeal is reviewed.", es: "Esta caja es mía hasta que se revise su reclamación." },
    { en: "You finished early. I suppose competence deserves company.", es: "Terminaste pronto. Supongo que la competencia merece compañía." },
    { en: "I have no objections to this particular scratch.", es: "No tengo objeciones a esta caricia en particular." },
    { en: "That loose thread is tempting. I remain professional.", es: "Ese hilo suelto es tentador. Mantengo la profesionalidad." },
    { en: "The welcome mat should welcome fewer muddy shoes.", es: "El felpudo debería dar la bienvenida a menos zapatos con barro." },
    { en: "I stayed late to supervise your safe departure.", es: "Me quedé hasta tarde para supervisar que salieras sin problemas." },
    { en: "Do not tell anyone I tucked the blanket around you.", es: "No le cuentes a nadie que te arropé con la manta." },
    { en: "The wool smells right. My report is complete.", es: "La lana huele como debe. Mi informe está terminado." },
    { en: "I dislike unnecessary fuss. Necessary fuss goes behind my ears.", es: "No me gustan los mimos innecesarios. Los necesarios van detrás de mis orejas." },
    { en: "You forgot to admire the finished hem.", es: "Olvidaste admirar el dobladillo terminado." },
    { en: "I am allowing this ribbon to live on my desk.", es: "Permito que esta cinta viva en mi escritorio." },
    { en: "Tomorrow, fewer interruptions. The same amount of you.", es: "Mañana, menos interrupciones. La misma cantidad de ti." },
    { en: "Well done. I will not be repeating myself.", es: "Buen trabajo. No voy a repetirlo." },
  ],
  mario: [
    { en: "Could you bring my nap a little closer?", es: "¿Podrías acercarme un poco la siesta?" },
    { en: "I thought kneading the blanket would make more blanket.", es: "Pensé que amasar la manta produciría más manta." },
    { en: "Your elbow makes a surprisingly good pillow.", es: "Tu codo es una almohada sorprendentemente buena." },
    { en: "I was helping. Then the helping became horizontal.", es: "Estaba ayudando. Luego la ayuda se volvió horizontal." },
    { en: "If I hug the basket, does that count as tidying?", es: "Si abrazo la cesta, ¿eso cuenta como ordenar?" },
    { en: "I saved you half the cushion. The underneath half.", es: "Te guardé la mitad del cojín. La mitad de abajo." },
    { en: "That yarn ball rolled away without taking me.", es: "Ese ovillo se fue rodando sin llevarme." },
    { en: "I nearly stood up. A very busy morning.", es: "Casi me puse de pie. Una mañana muy ocupada." },
    { en: "The pattern has steps. Must I walk them?", es: "El patrón tiene pasos. ¿Tengo que caminarlos?" },
    { en: "Please turn the page. My paw is comfortable here.", es: "Pasa la página, por favor. Mi pata está cómoda aquí." },
    { en: "I brought you a sock. Were we making socks?", es: "Te traje un calcetín. ¿Estábamos haciendo calcetines?" },
    { en: "Your apron pocket looks like a portable lap.", es: "El bolsillo de tu delantal parece un regazo portátil." },
    { en: "I lost count of stitches at the first yawn.", es: "Perdí la cuenta de los puntos en el primer bostezo." },
    { en: "The wool is brushed. Is it my turn?", es: "La lana está cepillada. ¿Me toca a mí?" },
    { en: "I can hold this corner down until next week.", es: "Puedo sujetar esta esquina hasta la semana que viene." },
    { en: "You sit. I arrive. That is our whole plan.", es: "Tú te sientas. Yo llego. Ese es todo nuestro plan." },
    { en: "I followed the thread and forgot the question.", es: "Seguí el hilo y olvidé la pregunta." },
    { en: "Do folded blankets get twice as much sleep?", es: "¿Las mantas dobladas duermen el doble?" },
    { en: "I am stretching toward you very, very gradually.", es: "Me estoy estirando hacia ti muy, muy despacio." },
    { en: "This sleeve already has a hand. Where do I go?", es: "Esta manga ya tiene una mano. ¿Dónde me pongo yo?" },
    { en: "My best contribution is making you stay seated.", es: "Mi mejor contribución es hacer que sigas en tu asiento." },
    { en: "I tried sorting colors. They were all soft.", es: "Intenté ordenar los colores. Todos eran suaves." },
    { en: "Carry me to the workbench. I will provide encouragement.", es: "Llévame a la mesa de trabajo. Yo daré ánimos." },
    { en: "I thought the measuring tape was a very flat scarf.", es: "Pensé que la cinta métrica era una bufanda muy plana." },
    { en: "You look busy. I could warm one of your feet.", es: "Parece que tienes mucho trabajo. Podría calentarte un pie." },
    { en: "I have been guarding this spool with my cheek.", es: "He estado vigilando este carrete con la mejilla." },
    { en: "The chair moved when you stood. That was unexpected.", es: "La silla se movió cuando te levantaste. No lo esperaba." },
    { en: "I planned to blink, but a nap happened.", es: "Pensaba parpadear, pero ocurrió una siesta." },
    { en: "Does a finished scarf need a cuddle to seal it?", es: "¿Una bufanda terminada necesita un abrazo para quedar lista?" },
    { en: "My tail is waving hello so I do not have to.", es: "Mi cola saluda para que yo no tenga que hacerlo." },
    { en: "I found a shortcut from your lap to your shoulder.", es: "Encontré un atajo de tu regazo a tu hombro." },
    { en: "The instruction says turn. I am facing you now.", es: "La instrucción dice girar. Ahora estoy mirando hacia ti." },
    { en: "I waited for the rocking chair to come to me.", es: "Esperé a que la mecedora viniera hacia mí." },
    { en: "This pile of scraps feels like a whole achievement.", es: "Este montón de retazos se siente como un gran logro." },
    { en: "Could our next errand happen on this cushion?", es: "¿Nuestro próximo recado podría ocurrir en este cojín?" },
    { en: "I helped warm the handles of your scissors. By accident.", es: "Ayudé a calentar los mangos de tus tijeras. Sin querer." },
    { en: "You said unwind. I thought we were already relaxing.", es: "Dijiste desenrollar. Yo creía que ya estábamos descansando." },
    { en: "My paw fits in your palm. Excellent planning.", es: "Mi pata cabe en tu palma. Excelente planificación." },
    { en: "I turned over the label. Still no treats.", es: "Le di la vuelta a la etiqueta. Sigue sin haber premios." },
    { en: "The empty spool looks tired. I understand it.", es: "El carrete vacío parece cansado. Lo comprendo." },
    { en: "I will keep your cardigan company while you work.", es: "Le haré compañía a tu chaqueta mientras trabajas." },
    { en: "I tried to chase a sunbeam. It was faster.", es: "Intenté perseguir un rayo de sol. Fue más rápido." },
    { en: "This drawer opens into another excellent lying-down place.", es: "Este cajón se abre a otro lugar excelente para acostarse." },
    { en: "Did you make that blanket for my nap or yours?", es: "¿Hiciste esa manta para mi siesta o para la tuya?" },
    { en: "I brought both paws. Was that enough help?", es: "Traje las dos patas. ¿Era suficiente ayuda?" },
    { en: "Your lap disappeared when you stood up. Is it safe?", es: "Tu regazo desapareció cuando te levantaste. ¿Está a salvo?" },
    { en: "A buttonhole is a window for buttons. I think.", es: "Un ojal es una ventana para botones. Creo." },
    { en: "I am on break from deciding when to start.", es: "Descanso de decidir cuándo empezar." },
    { en: "The stool has four legs and never takes walks.", es: "El taburete tiene cuatro patas y nunca sale a caminar." },
    { en: "I tucked my nose into your sleeve for safekeeping.", es: "Guardé mi nariz dentro de tu manga para protegerla." },
    { en: "Could you put the interesting thing within paw distance?", es: "¿Podrías poner esa cosa interesante al alcance de mi pata?" },
    { en: "I thought a wool blend meant we should cuddle it together.", es: "Pensé que una mezcla de lana se debía abrazar entre dos." },
    { en: "My eyes are shut, but my purr is available.", es: "Mis ojos están cerrados, pero mi ronroneo está disponible." },
    { en: "I fetched the same ribbon you were already holding.", es: "Te traje la misma cinta que ya estabas sujetando." },
    { en: "You knitted a pocket. Now the sweater has a basket.", es: "Tejiste un bolsillo. Ahora el suéter tiene una cesta." },
    { en: "I am waiting patiently for a very small belly rub.", es: "Espero con paciencia una caricia muy pequeña en la barriga." },
    { en: "I leaned on the fabric and ironed it with sleep.", es: "Me apoyé en la tela y la planché durmiendo." },
    { en: "If we whisper, perhaps the chores will stay asleep.", es: "Si susurramos, quizá las tareas sigan dormidas." },
    { en: "That tassel keeps tickling me. We are becoming friends.", es: "Esa borla sigue haciéndome cosquillas. Nos estamos haciendo amigos." },
    { en: "I looked for your pencil without moving my head.", es: "Busqué tu lápiz sin mover la cabeza." },
    { en: "The sweater is inside out. Does it feel shy?", es: "El suéter está al revés. ¿Le da vergüenza?" },
    { en: "I can cuddle you and the yarn simultaneously.", es: "Puedo abrazarte a ti y a la lana al mismo tiempo." },
    { en: "The shelf is high. I will admire it from here.", es: "El estante está alto. Lo admiraré desde aquí." },
    { en: "I thought the order number was how many naps remained.", es: "Pensé que el número del pedido indicaba cuántas siestas quedaban." },
    { en: "I woke up holding your thumb. Good choice, sleeping me.", es: "Desperté sujetando tu pulgar. Buena elección, yo dormido." },
    { en: "You made two mittens. Which one is for my tail?", es: "Hiciste dos manoplas. ¿Cuál es para mi cola?" },
    { en: "I would investigate that rustle, but your knee is warm.", es: "Investigaría ese crujido, pero tu rodilla está caliente." },
    { en: "A spool without thread is just a little stool.", es: "Un carrete sin hilo es solo un taburete pequeño." },
    { en: "Let us have a slow race to the nearest hug.", es: "Hagamos una carrera lenta hasta el abrazo más cercano." },
    { en: "I have been thinking about getting comfortable. Successfully.", es: "He estado pensando en ponerme cómodo. Con éxito." },
    { en: "You said keep an eye out. Mine keeps closing.", es: "Dijiste que estuviera atento. Se me siguen cerrando los ojos." },
    { en: "This fabric sample is small, but I believe in it.", es: "Esta muestra de tela es pequeña, pero confío en ella." },
    { en: "I sat on you because beside seemed too far away.", es: "Me senté sobre ti porque a tu lado parecía demasiado lejos." },
    { en: "Do we wind the yarn so it remembers being round?", es: "¿Enrollamos la lana para que recuerde ser redonda?" },
    { en: "I meant to hand you the ribbon. I am wearing it.", es: "Quería darte la cinta. La llevo puesta." },
    { en: "The quiet machine and I are working at equal speed.", es: "La máquina apagada y yo trabajamos a la misma velocidad." },
    { en: "I can follow your instructions if they lead to cuddles.", es: "Puedo seguir tus instrucciones si llevan a los abrazos." },
    { en: "This hem is folded. Should we tuck it in?", es: "Este dobladillo está plegado. ¿Deberíamos arroparlo?" },
    { en: "I moved one paw off your notebook. Progress.", es: "Quité una pata de tu cuaderno. Un avance." },
    { en: "I do not know what a swatch is. May I hug it?", es: "No sé qué es una muestra. ¿Puedo abrazarla?" },
    { en: "Could the basket come here when you finish filling it?", es: "¿Podría venir aquí la cesta cuando termines de llenarla?" },
    { en: "I kept your spot by spreading out considerably.", es: "Te guardé el sitio extendiéndome bastante." },
    { en: "The tape says ten. Ten what? Scratches?", es: "La cinta dice diez. ¿Diez qué? ¿Caricias?" },
    { en: "I dreamed I helped. Did the scarf get longer?", es: "Soñé que ayudaba. ¿La bufanda se hizo más larga?" },
    { en: "That little fabric heart fits right under my chin.", es: "Ese corazoncito de tela cabe justo debajo de mi barbilla." },
    { en: "I am saving my energy for an enthusiastic nuzzle.", es: "Estoy ahorrando energía para un roce cariñoso y entusiasta." },
    { en: "If you need me, gently rotate the cushion.", es: "Si me necesitas, gira el cojín con cuidado." },
    { en: "I thought closing the pattern meant the sweater was finished.", es: "Pensé que cerrar el patrón significaba terminar el suéter." },
    { en: "Your ankle makes this floor worth lying on.", es: "Tu tobillo hace que valga la pena acostarse en este suelo." },
    { en: "I can watch the doorway from either side of my face.", es: "Puedo mirar la puerta con cualquier lado de la cara apoyado." },
    { en: "That empty bag needs someone very relaxed inside.", es: "Esa bolsa vacía necesita a alguien muy relajado dentro." },
    { en: "I learned a new stitch. It might be a yawn.", es: "Aprendí un punto nuevo. Podría ser un bostezo." },
    { en: "We could fold the laundry around me and save time.", es: "Podríamos doblar la ropa a mi alrededor y ahorrar tiempo." },
    { en: "I trust you to know which end of me needs petting.", es: "Confío en que sepas qué extremo de mí necesita caricias." },
    { en: "Is a knitting row like cats sitting side by side?", es: "¿Una hilera de tejido es como gatos sentados en fila?" },
    { en: "I volunteered to be the soft thing on your desk.", es: "Me ofrecí para ser la cosa suave de tu escritorio." },
    { en: "The unfinished sleeve makes a very patient tunnel.", es: "La manga sin terminar es un túnel muy paciente." },
    { en: "I forgot why I came over. Let us cuddle anyway.", es: "Olvidé por qué me acerqué. Abracémonos de todos modos." },
    { en: "Please wake me when it is time to sleep beside you.", es: "Despiértame cuando sea hora de dormir a tu lado." },
    { en: "One more head rub and I might understand the pattern.", es: "Una caricia más en la cabeza y quizá entienda el patrón." },
  ],
  roman: [
    { en: "My belly has made a little valley in the cushion.", es: "Mi barriga ha formado un pequeño valle en el cojín." },
    { en: "Come rest your hand against my sleepy heartbeat.", es: "Ven a apoyar la mano sobre mi corazón soñoliento." },
    { en: "The basket fits me best when nobody measures.", es: "La cesta me queda mejor cuando nadie mide." },
    { en: "I woke up just to hear you say my name.", es: "Me desperté solo para oírte decir mi nombre." },
    { en: "This wool is almost as soft as my middle.", es: "Esta lana es casi tan suave como mi barriga." },
    { en: "I brought a very round shadow to the workshop.", es: "Traje una sombra muy redonda al taller." },
    { en: "There is room beside me if we both breathe gently.", es: "Hay sitio a mi lado si los dos respiramos despacio." },
    { en: "The lunch smell reached me before the lunch bell.", es: "El olor del almuerzo me llegó antes que la campanilla." },
    { en: "My purr sounds deeper when my cheek is squished.", es: "Mi ronroneo suena más grave cuando tengo la mejilla aplastada." },
    { en: "I fell asleep halfway through thanking you for breakfast.", es: "Me dormí a mitad de darte las gracias por el desayuno." },
    { en: "A wide scarf is simply a blanket with ambitions.", es: "Una bufanda ancha es una manta con ambiciones." },
    { en: "I can warm the whole cushion in one sitting.", es: "Puedo calentar todo el cojín de una sola sentada." },
    { en: "Your tired hands deserve a soft place to land.", es: "Tus manos cansadas merecen un lugar suave donde descansar." },
    { en: "I dreamed the yarn baskets were full of pillows.", es: "Soñé que las cestas de lana estaban llenas de almohadas." },
    { en: "This apron string has disappeared beneath my tummy.", es: "La cuerda de este delantal ha desaparecido bajo mi barriga." },
    { en: "I will lean lightly. Well, as lightly as possible.", es: "Me apoyaré con suavidad. Bueno, con la mayor suavidad posible." },
    { en: "The slow stitching rhythm is making my eyelids heavy.", es: "El ritmo lento de las puntadas me pesa en los párpados." },
    { en: "You smell like clean fabric and a good afternoon.", es: "Hueles a tela limpia y a una buena tarde." },
    { en: "My paws knead small circles. The rest of me relaxes.", es: "Mis patas amasan círculos pequeños. El resto de mí se relaja." },
    { en: "I saved a warm hollow just for your hand.", es: "Guardé un hueco cálido solo para tu mano." },
    { en: "The little stool and I reached a careful agreement.", es: "El taburete pequeño y yo llegamos a un acuerdo cuidadoso." },
    { en: "I like when the whole workshop settles after lunch.", es: "Me gusta cuando todo el taller se calma después del almuerzo." },
    { en: "The blanket fringe is tickling my round cheeks.", es: "Los flecos de la manta me hacen cosquillas en las mejillas redondas." },
    { en: "I missed one stitch and dreamed the next six.", es: "Me perdí un punto y soñé los seis siguientes." },
    { en: "Could you lift the blanket edge over my back?", es: "¿Podrías subir el borde de la manta sobre mi espalda?" },
    { en: "My chin found your knee before I finished yawning.", es: "Mi barbilla encontró tu rodilla antes de terminar el bostezo." },
    { en: "This box has become pleasantly snug since yesterday.", es: "Esta caja se ha vuelto agradablemente ajustada desde ayer." },
    { en: "I share my warmth more easily than my last crumb.", es: "Comparto mi calor con más facilidad que mi última miga." },
    { en: "Every time you laugh, my sleepy ears perk up.", es: "Cada vez que te ríes, mis orejas soñolientas se levantan." },
    { en: "The windowsill is narrow. My affection is not.", es: "El alféizar es estrecho. Mi cariño no." },
    { en: "I am listening to the soft thump of folded towels.", es: "Escucho el golpecito suave de las toallas al doblarse." },
    { en: "A full belly makes an excellent beginning to a nap.", es: "Una barriga llena es un excelente comienzo para una siesta." },
    { en: "Your scarf can borrow the curve of my back.", es: "Tu bufanda puede tomar prestada la curva de mi espalda." },
    { en: "I rolled toward you and took the blanket along.", es: "Rodé hacia ti y me llevé la manta." },
    { en: "My whiskers twitch when I dream of being brushed.", es: "Mis bigotes se mueven cuando sueño que me cepillan." },
    { en: "Let the rain count the minutes. We can rest.", es: "Deja que la lluvia cuente los minutos. Podemos descansar." },
    { en: "I am not stuck. The cushion is hugging me.", es: "No estoy atascado. El cojín me está abrazando." },
    { en: "There is a sleepy rumble beneath this much fluff.", es: "Hay un murmullo soñoliento bajo tanto pelo." },
    { en: "You can tell me about the order while I doze.", es: "Puedes contarme lo del pedido mientras dormito." },
    { en: "I have curled into a circle with a generous center.", es: "Me he hecho un círculo con un centro generoso." },
    { en: "The new cushion remembers my shape very quickly.", es: "El cojín nuevo aprende mi forma muy rápido." },
    { en: "I wish your worries were as easy to soften as wool.", es: "Ojalá tus preocupaciones fueran tan fáciles de ablandar como la lana." },
    { en: "I left a warm patch where the basket used to be.", es: "Dejé un sitio caliente donde antes estaba la cesta." },
    { en: "Your gentle brushing makes even my toes feel sleepy.", es: "Tu cepillado suave me da sueño hasta en los dedos." },
    { en: "I could smell the treat through two layers of fabric.", es: "Podía oler el premio a través de dos capas de tela." },
    { en: "This nap needs the quiet sound of you nearby.", es: "Esta siesta necesita el sonido tranquilo de ti cerca." },
    { en: "I bent to wash my belly and paused for reflection.", es: "Me incliné para lavarme la barriga y me detuve a reflexionar." },
    { en: "The warm folded sheet feels fresh from a dream.", es: "La sábana tibia y doblada parece recién salida de un sueño." },
    { en: "I like your slow days. There is more leaning time.", es: "Me gustan tus días tranquilos. Hay más tiempo para apoyarme en ti." },
    { en: "My cheek has flattened one very lucky tassel.", es: "Mi mejilla ha aplastado una borla muy afortunada." },
    { en: "You tucked me in so well I forgot the weather.", es: "Me arropaste tan bien que olvidé el tiempo que hacía." },
    { en: "I left the narrow passage to the narrower cats.", es: "Dejé el pasillo estrecho para los gatos más estrechos." },
    { en: "My drowsy greeting comes with both cheeks.", es: "Mi saludo soñoliento viene con las dos mejillas." },
    { en: "That extra stitch gives the hat a little breathing room.", es: "Ese punto extra le da al gorro un poco de espacio." },
    { en: "The good nap began before the workshop clock chimed.", es: "La buena siesta empezó antes de que sonara el reloj del taller." },
    { en: "I pressed my nose to your wrist to say thanks.", es: "Apreté la nariz contra tu muñeca para darte las gracias." },
    { en: "The basket handle leaves a funny parting in my fur.", es: "El asa de la cesta me deja una raya curiosa en el pelo." },
    { en: "Your humming feels like another layer of blanket.", es: "Tu tarareo se siente como otra capa de manta." },
    { en: "I heard the food jar even through a beautiful dream.", es: "Oí el frasco de comida incluso en medio de un sueño hermoso." },
    { en: "I will be your soft landing after a long order.", es: "Seré tu descanso suave después de un pedido largo." },
    { en: "My sleeping paws are still politely crossed.", es: "Mis patas dormidas siguen cruzadas con educación." },
    { en: "The tablecloth reaches me now. It makes a fine canopy.", es: "El mantel ya llega hasta mí. Forma un dosel estupendo." },
    { en: "I remember when this basket had spare room.", es: "Recuerdo cuando sobraba espacio en esta cesta." },
    { en: "I blinked slowly so you would know I felt safe.", es: "Parpadeé despacio para que supieras que me sentía seguro." },
    { en: "The wool pile sighs a little when I settle.", es: "El montón de lana suspira un poco cuando me acomodo." },
    { en: "I cannot reach that itch. You know the one.", es: "No alcanzo ese picor. Ya sabes cuál." },
    { en: "I would like my afternoon served with a forehead kiss.", es: "Me gustaría que mi tarde viniera con un beso en la frente." },
    { en: "My tummy rose and lowered the ribbon like a tiny tide.", es: "Mi barriga subía y bajaba la cinta como una pequeña marea." },
    { en: "You finished the sleeve while I finished a lovely dream.", es: "Terminaste la manga mientras yo terminaba un sueño precioso." },
    { en: "I stayed curled around the cushion after you took it away.", es: "Seguí acurrucado alrededor del cojín después de que lo retiraras." },
    { en: "A second breakfast would fit nicely before my second nap.", es: "Un segundo desayuno encajaría bien antes de mi segunda siesta." },
    { en: "I am making the workshop quieter, one sleepy breath at a time.", es: "Estoy calmando el taller, una respiración soñolienta a la vez." },
    { en: "Your fingers disappeared into my neck fluff again.", es: "Tus dedos desaparecieron otra vez entre el pelo de mi cuello." },
    { en: "The little wool cloud beside me is shed fur. Mine.", es: "La nubecita de lana a mi lado es pelo suelto. Mío." },
    { en: "I like being carried with a hand under my bottom.", es: "Me gusta que me carguen con una mano bajo el trasero." },
    { en: "The cushion cover stretches kindly around all of me.", es: "La funda del cojín se estira con amabilidad a mi alrededor." },
    { en: "I opened one eye to admire your finished blanket.", es: "Abrí un ojo para admirar tu manta terminada." },
    { en: "There is a button-shaped dent in my sleeping spot.", es: "Hay una marca con forma de botón donde dormía." },
    { en: "I will keep purring until your shoulders stop feeling tight.", es: "Seguiré ronroneando hasta que tus hombros dejen de estar tensos." },
    { en: "My nap lasted exactly one neatly wound ball of yarn.", es: "Mi siesta duró exactamente un ovillo de lana bien enrollado." },
    { en: "This warm floor makes standing up feel unnecessary.", es: "Este suelo cálido hace que levantarse parezca innecesario." },
    { en: "Your palm is just the right size for my round forehead.", es: "Tu palma tiene el tamaño justo para mi frente redonda." },
    { en: "I waddled over because you sounded like you needed company.", es: "Vine contoneándome porque parecía que necesitabas compañía." },
    { en: "The shop is dim now. My whiskers are getting heavy.", es: "El taller tiene poca luz. Me empiezan a pesar los bigotes." },
    { en: "I dreamed your unfinished quilt had room for everyone.", es: "Soñé que tu colcha sin terminar tenía sitio para todos." },
    { en: "My belly covered the pattern, but I left the picture.", es: "Mi barriga cubrió el patrón, pero dejé la ilustración." },
    { en: "I would rather have your company than the bigger basket.", es: "Prefiero tu compañía a la cesta más grande." },
    { en: "The treat was small. My grateful purr was not.", es: "El premio era pequeño. Mi ronroneo agradecido no." },
    { en: "I settled against the doorstop and became a softer doorstop.", es: "Me apoyé en el tope de la puerta y me convertí en uno más suave." },
    { en: "The blanket slipped, and my pink tummy greeted the room.", es: "La manta se deslizó y mi barriga rosada saludó a la habitación." },
    { en: "You may borrow my warmth until the kettle settles.", es: "Puedes tomar prestado mi calor hasta que la tetera deje de sonar." },
    { en: "I gave the yarn a sleepy nose bump for luck.", es: "Le di a la lana un golpecito soñoliento con la nariz para darle suerte." },
    { en: "The broad bench lets me stretch without choosing a direction.", es: "El banco ancho me deja estirarme sin tener que elegir una dirección." },
    { en: "I am saving this gentle moment somewhere behind my purr.", es: "Guardo este momento tierno en algún lugar detrás de mi ronroneo." },
    { en: "My yawn surprised a loose curl of wool.", es: "Mi bostezo sorprendió a un rizo de lana suelto." },
    { en: "The cushion seam has traveled halfway around me.", es: "La costura del cojín ha dado media vuelta a mi alrededor." },
    { en: "I like when you say goodnight before dimming the lamp.", es: "Me gusta que digas buenas noches antes de bajar la lámpara." },
    { en: "I leaned in for a nuzzle and forgot to lean away.", es: "Me acerqué para darte un roce cariñoso y olvidé apartarme." },
    { en: "A gentle pat is enough to send me dreaming again.", es: "Una palmadita suave basta para que vuelva a soñar." },
    { en: "All this softness is happier when you are here.", es: "Toda esta suavidad es más feliz cuando estás aquí." },
  ],
  luigi: [
    { en: "I will stand here until the shelf stops wobbling.", es: "Me quedaré aquí hasta que el estante deje de tambalearse." },
    { en: "It is my turn for attention. I can wait on your work.", es: "Me toca recibir atención. Puedo esperar encima de tu trabajo." },
    { en: "The little ones can walk behind my tail.", es: "Los pequeños pueden caminar detrás de mi cola." },
    { en: "I look larger when the workshop door lets in a draft.", es: "Parezco más grande cuando entra aire por la puerta del taller." },
    { en: "Set the heavy basket down. I can wait beside it.", es: "Deja la cesta pesada en el suelo. Puedo esperar a su lado." },
    { en: "Nobody has to cross the slippery floor alone.", es: "Nadie tiene que cruzar el suelo resbaladizo a solas." },
    { en: "That ribbon started it. I am simply finishing the game.", es: "La cinta empezó. Yo solo estoy terminando el juego." },
    { en: "Take your time with the knot. We are not leaving.", es: "Tómate tu tiempo con el nudo. No nos vamos a ir." },
    { en: "I checked the doorway. There is room for everyone.", es: "Revisé la entrada. Hay espacio para todos." },
    { en: "A steady paw is more useful than a loud meow.", es: "Una pata firme es más útil que un maullido fuerte." },
    { en: "I keep my promises and my fur very full.", es: "Mantengo mis promesas y mi pelo bien abundante." },
    { en: "That fallen spool can wait until the cart passes.", es: "Ese carrete caído puede esperar hasta que pase el carrito." },
    { en: "I asked for a scratch. This paw is your reminder.", es: "Pedí una caricia. Esta pata es un recordatorio." },
    { en: "New visitors may offer a hand. I will sniff first.", es: "Las visitas nuevas pueden ofrecer una mano. Yo oleré primero." },
    { en: "The rain is loud. My breathing will stay quiet.", es: "La lluvia suena fuerte. Mi respiración seguirá tranquila." },
    { en: "I found the missing kitten beneath the fabric samples.", es: "Encontré al gatito perdido debajo de las muestras de tela." },
    { en: "You can start again. I will watch the first stitch.", es: "Puedes empezar de nuevo. Vigilaré el primer punto." },
    { en: "This path stays clear, even if the ribbons disagree.", es: "Este camino queda despejado, aunque las cintas no estén de acuerdo." },
    { en: "My chest is fluffy enough for a worried forehead.", es: "Mi pecho es lo bastante mullido para una frente preocupada." },
    { en: "Let the customer finish speaking. Then we can help.", es: "Deja que el cliente termine de hablar. Después podremos ayudar." },
    { en: "I tested the step before inviting Lola up.", es: "Probé el escalón antes de invitar a Lola a subir." },
    { en: "Loose threads belong away from little paws.", es: "Los hilos sueltos deben quedar lejos de las patitas." },
    { en: "You moved my cushion. I have moved it back.", es: "Moviste mi cojín. Ya lo he puesto de nuevo en su sitio." },
    { en: "There is no shame in choosing the lower shelf.", es: "No hay vergüenza en elegir el estante más bajo." },
    { en: "I will escort the empty basket back to its corner.", es: "Acompañaré la cesta vacía hasta su rincón." },
    { en: "The door latch clicked. Our evening can begin.", es: "El pestillo de la puerta sonó. Ya puede empezar nuestra tarde." },
    { en: "My collar sits straight. The rest is gloriously fluffy.", es: "Mi collar está derecho. El resto es maravillosamente esponjoso." },
    { en: "I will sit between the sleeping cats and the bustle.", es: "Me sentaré entre los gatos dormidos y el ajetreo." },
    { en: "That tiny meow deserves our full attention.", es: "Ese maullido diminuto merece toda nuestra atención." },
    { en: "We can share the workbench without sharing the same inch.", es: "Podemos compartir la mesa sin ocupar el mismo centímetro." },
    { en: "I prefer to settle disagreements with extra cushions.", es: "Prefiero resolver los desacuerdos con cojines adicionales." },
    { en: "Put the sharp things away before the evening stretch.", es: "Guarda las cosas afiladas antes del estiramiento de la tarde." },
    { en: "I know this workshop by the feel under my paws.", es: "Conozco este taller por lo que siento bajo las patas." },
    { en: "Someone small is sleeping here. Walk softly.", es: "Alguien pequeño duerme aquí. Camina con suavidad." },
    { en: "I brought my whole fluffy self to this tiny gap.", es: "He traído todo mi pelo a este hueco diminuto." },
    { en: "My mane caught the ribbon. I shall wear it calmly.", es: "Mi melena atrapó la cinta. La llevaré con calma." },
    { en: "I will hold the fabric steady while you smooth it.", es: "Sujetaré la tela mientras tú la alisas." },
    { en: "The tallest pile is not always the safest perch.", es: "El montón más alto no siempre es el lugar más seguro." },
    { en: "I am here for the quiet cats, too.", es: "También estoy aquí para los gatos callados." },
    { en: "The big box can shelter more than one small dream.", es: "La caja grande puede cobijar más de un sueño pequeño." },
    { en: "I will let you know when the delivery arrives.", es: "Te avisaré cuando llegue la entrega." },
    { en: "One careful step beats two hurried slips.", es: "Un paso cuidadoso vale más que dos resbalones apresurados." },
    { en: "My fluffy shoulder is available if you need courage.", es: "Mi hombro esponjoso está disponible si necesitas valor." },
    { en: "I heard a startled squeak. Let us check gently.", es: "Oí un chillido de sorpresa. Vamos a revisar con calma." },
    { en: "We make room for nervous paws at this table.", es: "En esta mesa hacemos sitio para las patas nerviosas." },
    { en: "I can wait outside the basket until you feel ready.", es: "Puedo esperar fuera de la cesta hasta que te sientas listo." },
    { en: "I am helping whether the basket asked or not.", es: "Estoy ayudando, aunque la cesta no lo haya pedido." },
    { en: "I will face the noisy hallway so you need not.", es: "Miraré hacia el pasillo ruidoso para que tú no tengas que hacerlo." },
    { en: "My tail signals the safe way around the ladder.", es: "Mi cola señala el camino seguro alrededor de la escalera." },
    { en: "The warm spot belongs to whoever needs it most.", es: "El sitio cálido es para quien más lo necesite." },
    { en: "You asked for support. I brought all four paws.", es: "Pediste apoyo. Traje las cuatro patas." },
    { en: "We can admire the high windows without climbing the curtains.", es: "Podemos admirar las ventanas altas sin trepar por las cortinas." },
    { en: "I make sure the quiet farewell gets heard.", es: "Me aseguro de que se escuche la despedida más suave." },
    { en: "My fur is impressive. My patience is even better.", es: "Mi pelo impresiona. Mi paciencia es aún mejor." },
    { en: "Leave the basket handle upright so nobody trips.", es: "Deja el asa de la cesta levantada para que nadie tropiece." },
    { en: "You can trust me with the very last yarn ball.", es: "Puedes confiarme el último ovillo de lana." },
    { en: "The new sewing machine startled us. Now we know its voice.", es: "La máquina nueva nos sobresaltó. Ahora conocemos su voz." },
    { en: "I will not crowd you while you learn.", es: "No te agobiaré mientras aprendes." },
    { en: "One more head bump. You looked insufficiently cuddled.", es: "Un cabezazo más. Parecía que te faltaban mimos." },
    { en: "My paws stay planted when the doorbell rings.", es: "Mis patas se mantienen firmes cuando suena la campanilla." },
    { en: "We will untangle Biscuit before sorting the yarn.", es: "Desenredaremos a Biscuit antes de ordenar la lana." },
    { en: "I am tall enough to check the empty counter.", es: "Soy lo bastante alto para revisar el mostrador vacío." },
    { en: "Your tired voice matters as much as your cheerful one.", es: "Tu voz cansada importa tanto como tu voz alegre." },
    { en: "I keep a soft watch while the others dream.", es: "Vigilo con suavidad mientras los demás sueñan." },
    { en: "No one needs to squeeze past the stacked parcels.", es: "Nadie tiene que apretarse para pasar junto a los paquetes apilados." },
    { en: "I accept hugs. Ask with an open hand.", es: "Acepto abrazos. Pídelos con una mano abierta." },
    { en: "This cracked basket edge needs fixing before another nap.", es: "Hay que arreglar este borde roto de la cesta antes de otra siesta." },
    { en: "I remember where each sleepy friend likes to rest.", es: "Recuerdo dónde le gusta descansar a cada amigo soñoliento." },
    { en: "There is enough wool. We can make another scarf.", es: "Hay suficiente lana. Podemos hacer otra bufanda." },
    { en: "I choose the solid bench, not the impressive wobble.", es: "Elijo el banco firme, no el tambaleo impresionante." },
    { en: "I can be very firm about sitting next to you.", es: "Puedo ser muy firme cuando quiero sentarme a tu lado." },
    { en: "My thick ruff catches dust before it reaches my neck.", es: "Mi cuello de pelo espeso atrapa el polvo antes de que llegue a mi piel." },
    { en: "I will wait until every paw is inside.", es: "Esperaré hasta que todas las patas estén dentro." },
    { en: "We can lower the lamp if the light bothers you.", es: "Podemos bajar la lámpara si la luz te molesta." },
    { en: "I know when to step forward and when to stay close.", es: "Sé cuándo dar un paso al frente y cuándo quedarme cerca." },
    { en: "The rushing can stop here. This corner is calm.", es: "Las prisas pueden terminar aquí. Este rincón está tranquilo." },
    { en: "I moved aside so the smaller cat could see.", es: "Me aparté para que el gato más pequeño pudiera ver." },
    { en: "My whiskers found the narrow gap before my shoulders did.", es: "Mis bigotes encontraron el hueco estrecho antes que mis hombros." },
    { en: "I will keep the blanket from sliding off the bench.", es: "Evitaré que la manta se deslice del banco." },
    { en: "Your first try belongs on the shelf with the others.", es: "Tu primer intento merece estar en el estante con los demás." },
    { en: "I do not need the highest seat to look after everyone.", es: "No necesito el asiento más alto para cuidar a todos." },
    { en: "That rustling bag is empty. Come see with me.", es: "Esa bolsa que cruje está vacía. Ven a verla conmigo." },
    { en: "If that spool rolls again, we are having a discussion.", es: "Si ese carrete vuelve a rodar, tendremos una conversación." },
    { en: "I noticed the loose floor mat. We should straighten it.", es: "Noté que el felpudo está suelto. Deberíamos enderezarlo." },
    { en: "I am proud of the way you tried again.", es: "Estoy orgulloso de cómo volviste a intentarlo." },
    { en: "The brush pulled a little. Slower is better.", es: "El cepillo tiró un poco. Más despacio es mejor." },
    { en: "I will leave the doorway wide enough for Roman.", es: "Dejaré la entrada lo bastante despejada para Roman." },
    { en: "The workshop sounds different tonight. I will stay nearby.", es: "El taller suena distinto esta noche. Me quedaré cerca." },
    { en: "We can welcome a new friend without moving your bed.", es: "Podemos recibir a un amigo nuevo sin mover tu cama." },
    { en: "My calm is yours to borrow during the busy hour.", es: "Puedes tomar prestada mi calma durante la hora de más trabajo." },
    { en: "That bundle is slipping. Set it down before continuing.", es: "Ese paquete se está resbalando. Déjalo en el suelo antes de seguir." },
    { en: "I listen all the way to the end of a meow.", es: "Escucho cada maullido hasta el final." },
    { en: "There is strength in letting the smaller paws lead.", es: "Hay fuerza en dejar que las patas más pequeñas guíen." },
    { en: "My coat needs brushing, but nobody else needs hurrying.", es: "Mi pelo necesita un cepillado, pero nadie necesita que lo apresuren." },
    { en: "I borrowed your sleeve. You may keep the rest.", es: "Tomé prestada tu manga. Puedes quedarte con el resto." },
    { en: "I saw you set the scissors safely aside. Thank you.", es: "Vi que dejaste las tijeras a un lado con cuidado. Gracias." },
    { en: "I can guard your rest without interrupting your dreams.", es: "Puedo cuidar tu descanso sin interrumpir tus sueños." },
    { en: "The last parcel is ready. Let us clear the walkway.", es: "El último paquete está listo. Despejemos el paso." },
    { en: "My fluffy silhouette means you have company at the door.", es: "Mi silueta esponjosa significa que tienes compañía en la puerta." },
    { en: "Everything is settled. You can let your paws relax.", es: "Todo está en orden. Ya puedes relajar las patas." },
  ],
  lola: [
    { en: "I found a heart in the shape of this scrap.", es: "Encontré un corazón en la forma de este retazo." },
    { en: "May I sit close enough for our shadows to touch?", es: "¿Puedo sentarme lo bastante cerca para que nuestras sombras se toquen?" },
    { en: "The smallest bow fits between my two ears.", es: "El lazo más pequeño cabe entre mis dos orejas." },
    { en: "I left a tiny thank-you purr in your pocket.", es: "Dejé un pequeño ronroneo de agradecimiento en tu bolsillo." },
    { en: "Your stitches look like little footsteps staying together.", es: "Tus puntadas parecen pasitos que se mantienen juntos." },
    { en: "I can hear the ribbon whisper against the paper.", es: "Oigo a la cinta susurrar contra el papel." },
    { en: "This button is the same pink as my nose.", es: "Este botón tiene el mismo rosa que mi nariz." },
    { en: "I like the gentle way you fold the corners.", es: "Me gusta la delicadeza con que doblas las esquinas." },
    { en: "There is a whole cozy world beneath your chair.", es: "Hay todo un mundo acogedor debajo de tu silla." },
    { en: "Could you lower your hand? I have a nuzzle ready.", es: "¿Podrías bajar la mano? Tengo listo un roce cariñoso." },
    { en: "The lace makes little flowers of light on the floor.", es: "El encaje dibuja pequeñas flores de luz en el suelo." },
    { en: "I saved this soft scrap for someone who needs it.", es: "Guardé este retazo suave para quien lo necesite." },
    { en: "My paws barely wrinkle the freshly folded fabric.", es: "Mis patas apenas arrugan la tela recién doblada." },
    { en: "The new scarf looks like it wants to keep someone warm.", es: "La bufanda nueva parece querer abrigar a alguien." },
    { en: "I practice my bravest meow when the shop is quiet.", es: "Practico mi maullido más valiente cuando el taller está tranquilo." },
    { en: "A little ribbon curl is waving at me.", es: "Un pequeño rizo de cinta me está saludando." },
    { en: "I can fit beside the basket without moving anything.", es: "Puedo acomodarme junto a la cesta sin mover nada." },
    { en: "Your sewing song has a very kind ending.", es: "Tu canción de costura tiene un final muy dulce." },
    { en: "I touched the wool with just one careful toe.", es: "Toqué la lana con un solo dedito cuidadoso." },
    { en: "May I be the first to admire your new pattern?", es: "¿Puedo ser la primera en admirar tu patrón nuevo?" },
    { en: "The pale thread almost disappears in the morning light.", es: "El hilo claro casi desaparece con la luz de la mañana." },
    { en: "I brought a quiet hello for the shy visitor.", es: "Traje un saludo suave para la visita tímida." },
    { en: "My little reflection fits inside the shiny button.", es: "Mi pequeño reflejo cabe dentro del botón brillante." },
    { en: "The empty thimble looks like a tiny flowerpot.", es: "El dedal vacío parece una maceta diminuta." },
    { en: "I like when you leave the good scraps for patchwork.", es: "Me gusta que guardes los retazos buenos para el trabajo de parches." },
    { en: "Your fingertip is just enough for my forehead.", es: "La punta de tu dedo basta para mi frente." },
    { en: "The wool smells faintly of the wooden shelf.", es: "La lana huele un poquito al estante de madera." },
    { en: "I found a place where the big blanket folds into a cave.", es: "Encontré un sitio donde la manta grande se dobla formando una cueva." },
    { en: "I hope the person who wears this feels loved.", es: "Espero que quien use esto se sienta querido." },
    { en: "A single loose stitch can become a little loop to admire.", es: "Un solo punto suelto puede formar un pequeño bucle para admirar." },
    { en: "My whiskers tremble when you say something sweet.", es: "Mis bigotes tiemblan cuando dices algo dulce." },
    { en: "I sat on the corner so your drawing would not curl.", es: "Me senté en la esquina para que tu dibujo no se enrollara." },
    { en: "The softest fabric makes almost no sound at all.", es: "La tela más suave casi no hace ningún sonido." },
    { en: "Could we put a tiny ribbon on the gift?", es: "¿Podríamos ponerle una cinta pequeñita al regalo?" },
    { en: "I am learning which footsteps mean you are coming back.", es: "Estoy aprendiendo qué pasos significan que vuelves." },
    { en: "The low shelf lets me see all the pretty colors.", es: "El estante bajo me deja ver todos los colores bonitos." },
    { en: "I left the larger cushion for a larger friend.", es: "Dejé el cojín más grande para un amigo más grande." },
    { en: "Your careful repairs make old things feel wanted again.", es: "Tus arreglos cuidadosos hacen que las cosas viejas se sientan queridas otra vez." },
    { en: "The folded napkin looks like a little sleeping bird.", es: "La servilleta doblada parece un pajarito dormido." },
    { en: "I can wait while you finish that delicate stitch.", es: "Puedo esperar mientras terminas esa puntada delicada." },
    { en: "My tiny sneeze made the tissue paper flutter.", es: "Mi estornudo diminuto hizo ondear el papel de seda." },
    { en: "A soft voice reaches my ears better than a loud one.", es: "Una voz suave llega mejor a mis oídos que una fuerte." },
    { en: "I love the little knot hiding underneath a perfect bow.", es: "Me encanta el nudito escondido debajo de un lazo perfecto." },
    { en: "The window mist has room for one small nose print.", es: "El vaho de la ventana tiene sitio para una huella de nariz pequeña." },
    { en: "May I keep you company during the last few stitches?", es: "¿Puedo acompañarte durante las últimas puntadas?" },
    { en: "Your pencil left a tiny star beside the measurements.", es: "Tu lápiz dejó una estrellita junto a las medidas." },
    { en: "I think the yellow wool makes this corner feel sunny.", es: "Creo que la lana amarilla hace que este rincón parezca soleado." },
    { en: "My tail can curl neatly around just one paw.", es: "Mi cola puede rodear con cuidado una sola pata." },
    { en: "I tucked the little fabric doll beneath a scrap blanket.", es: "Arropé la muñequita de tela con una manta de retazos." },
    { en: "That quiet smile was worth climbing down for.", es: "Esa sonrisa tranquila merecía que bajara a verla." },
    { en: "The fringe brushes my back like the gentlest greeting.", es: "Los flecos me rozan la espalda como el saludo más suave." },
    { en: "I like the almost-silent click of your wooden buttons.", es: "Me gusta el clic casi silencioso de tus botones de madera." },
    { en: "This little patch will help the old quilt last longer.", es: "Este pequeño parche ayudará a que la colcha vieja dure más." },
    { en: "I am small enough to admire the underside of the table.", es: "Soy lo bastante pequeña para admirar la parte de abajo de la mesa." },
    { en: "A ribbon shadow drew a little road to your shoe.", es: "La sombra de una cinta dibujó un caminito hasta tu zapato." },
    { en: "You made that uneven stitch with such careful hands.", es: "Hiciste esa puntada desigual con tanto cuidado." },
    { en: "I have a small purr for your smallest victories.", es: "Tengo un ronroneo pequeño para tus victorias más pequeñas." },
    { en: "The felt flower does not smell, but I like it.", es: "La flor de fieltro no tiene olor, pero me gusta." },
    { en: "My paws found the tiniest warm tile.", es: "Mis patas encontraron la baldosa cálida más pequeña." },
    { en: "I wish every parcel could carry a little kindness.", es: "Ojalá cada paquete pudiera llevar un poco de cariño." },
    { en: "The blue thread reminds me of the sky through our window.", es: "El hilo azul me recuerda al cielo de nuestra ventana." },
    { en: "I moved carefully so the sleeping cats would not stir.", es: "Me moví con cuidado para no despertar a los gatos dormidos." },
    { en: "Your apron hem makes a lovely curtain for my hideaway.", es: "El borde de tu delantal es una cortina preciosa para mi escondite." },
    { en: "I found two matching buttons and placed them together.", es: "Encontré dos botones iguales y los puse juntos." },
    { en: "May I rest my cheek on your open palm?", es: "¿Puedo apoyar la mejilla en tu palma abierta?" },
    { en: "The stitched leaf has little veins, just like a real one.", es: "La hoja bordada tiene venitas, igual que una de verdad." },
    { en: "I can see the lamp reflected in your needle case.", es: "Veo la lámpara reflejada en tu estuche de agujas." },
    { en: "This short piece of yarn could still tie a lovely bow.", es: "Este trocito de lana aún podría formar un lazo bonito." },
    { en: "I say good morning to the workshop before anyone arrives.", es: "Le doy los buenos días al taller antes de que llegue nadie." },
    { en: "The soft package paper is almost the color of my ears.", es: "El papel suave del paquete casi tiene el color de mis orejas." },
    { en: "Your hand stayed nearby until I felt brave enough.", es: "Dejaste la mano cerca hasta que me sentí valiente." },
    { en: "I like that your handmade things are never quite identical.", es: "Me gusta que tus cosas hechas a mano nunca sean del todo iguales." },
    { en: "A tiny space between the cushions feels made for me.", es: "Un huequito entre los cojines parece hecho para mí." },
    { en: "The embroidered moon is small enough to sleep beside.", es: "La luna bordada es lo bastante pequeña para dormir a su lado." },
    { en: "I heard you thank the delivery person. It sounded warm.", es: "Te oí agradecer a quien trajo el pedido. Sonó muy amable." },
    { en: "My nose followed the velvet in its softer direction.", es: "Mi nariz siguió el terciopelo en su dirección más suave." },
    { en: "The gift tag has room for one more little heart.", es: "La etiqueta del regalo tiene sitio para un corazoncito más." },
    { en: "I will keep this shy new spool company.", es: "Le haré compañía a este carrete nuevo y tímido." },
    { en: "Your careful fingers make the tiniest repairs look important.", es: "Tus dedos cuidadosos hacen que los arreglos más pequeños parezcan importantes." },
    { en: "I peeked over the basket and saw you smiling.", es: "Me asomé sobre la cesta y vi tu sonrisa." },
    { en: "The white thread caught the light for just a moment.", es: "El hilo blanco atrapó la luz solo un instante." },
    { en: "I prefer the little brush. It knows all my corners.", es: "Prefiero el cepillo pequeño. Conoce todos mis rincones." },
    { en: "The leftover fabric became something lovely after all.", es: "La tela sobrante se convirtió en algo bonito al final." },
    { en: "You whispered my name so gently that I came closer.", es: "Susurraste mi nombre con tanta dulzura que me acerqué." },
    { en: "I watched the last drop slide down the workshop window.", es: "Vi la última gota deslizarse por la ventana del taller." },
    { en: "My small paw can hold the edge of your large dream.", es: "Mi patita puede sujetar el borde de tu gran sueño." },
    { en: "The mended seam feels like a place that healed.", es: "La costura reparada se siente como un lugar que sanó." },
    { en: "I found a tiny feather of wool on your sleeve.", es: "Encontré una plumita de lana en tu manga." },
    { en: "Could we leave the small lamp on a little longer?", es: "¿Podríamos dejar la lámpara pequeña encendida un poco más?" },
    { en: "The cushion smells like all the friends who shared it.", es: "El cojín huele a todos los amigos que lo compartieron." },
    { en: "I like the pause before you choose the next color.", es: "Me gusta la pausa antes de que elijas el siguiente color." },
    { en: "This ribbon end looks like a little open hand.", es: "El extremo de esta cinta parece una manita abierta." },
    { en: "I stood on tiptoe to give your wrist a kiss.", es: "Me puse de puntillas para darle un beso a tu muñeca." },
    { en: "The finished patchwork has a home for every little piece.", es: "El trabajo de parches terminado tiene un hogar para cada trocito." },
    { en: "I can sit quietly with the things you have not finished.", es: "Puedo sentarme en silencio junto a las cosas que aún no has terminado." },
    { en: "Your soft goodnight makes the whole room feel smaller.", es: "Tus buenas noches suaves hacen que toda la habitación parezca más pequeña." },
    { en: "I left one careful paw print in the velvet.", es: "Dejé una huella cuidadosa en el terciopelo." },
    { en: "The first stitch was tiny. Look how far it traveled.", es: "El primer punto era diminuto. Mira cuánto ha avanzado." },
    { en: "I am happy this busy workshop has a place for me.", es: "Me alegra que este taller ajetreado tenga un lugar para mí." },
    { en: "My love fits in small places, but it keeps growing.", es: "Mi cariño cabe en lugares pequeños, pero sigue creciendo." },
  ],
  biscocho: [
    { en: "I untangled one paw and discovered two more problems.", es: "Desenredé una pata y descubrí dos problemas más." },
    { en: "This yarn followed me. I did not invite it.", es: "Esta lana me siguió. Yo no la invité." },
    { en: "I tried to sit gracefully. The ribbons applauded loudly.", es: "Intenté sentarme con elegancia. Las cintas aplaudieron muy fuerte." },
    { en: "Is the basket wearing me, or am I wearing it?", es: "¿La cesta me lleva puesta o yo la llevo puesta?" },
    { en: "I returned the spool. It returned right back.", es: "Devolví el carrete. Volvió enseguida hacia mí." },
    { en: "The pattern said loop. I may have become one.", es: "El patrón decía bucle. Puede que me haya convertido en uno." },
    { en: "I found the end of the thread. It has friends.", es: "Encontré el extremo del hilo. Tiene amigos." },
    { en: "My tail has a bow. Nobody remembers making it.", es: "Mi cola tiene un lazo. Nadie recuerda haberlo hecho." },
    { en: "I sneezed into the scraps and made a small snowfall.", es: "Estornudé sobre los retazos y creé una pequeña nevada." },
    { en: "The floor was clear before I tried to help.", es: "El suelo estaba despejado antes de que intentara ayudar." },
    { en: "I meant to catch the ribbon, not the whole display.", es: "Quería atrapar la cinta, no todo el escaparate." },
    { en: "Why does this thread get longer when I leave?", es: "¿Por qué este hilo se alarga cuando me voy?" },
    { en: "I put my paw through the handle. Now we travel together.", es: "Metí la pata por el asa. Ahora viajamos juntos." },
    { en: "The little bell startled me into ringing it again.", es: "La campanilla me sobresaltó y terminé haciéndola sonar otra vez." },
    { en: "I have reorganized the colors into one confusing color.", es: "He reorganizado los colores en un solo color confuso." },
    { en: "This button rolled under me. I have become its cupboard.", es: "Este botón rodó debajo de mí. Me he convertido en su armario." },
    { en: "I tried walking backward. The yarn preferred forward.", es: "Intenté caminar hacia atrás. La lana prefirió ir hacia delante." },
    { en: "Your measuring tape is hugging all four of my ankles.", es: "Tu cinta métrica está abrazando mis cuatro tobillos." },
    { en: "I think my left paw belongs to the knitting now.", es: "Creo que mi pata izquierda ya pertenece al tejido." },
    { en: "The empty box sounded less empty after I fell in.", es: "La caja vacía sonó menos vacía después de que cayera dentro." },
    { en: "I fetched your pencil and also the paper beneath it.", es: "Te traje el lápiz y también el papel que había debajo." },
    { en: "Was that a tassel? I already apologized to it.", es: "¿Eso era una borla? Ya le pedí perdón." },
    { en: "I stepped over the thread. Then over it again. Somehow.", es: "Pasé por encima del hilo. Luego otra vez. No sé cómo." },
    { en: "The ribbon curled around my nose during our introduction.", es: "La cinta se enroscó en mi nariz cuando nos presentamos." },
    { en: "I landed in the laundry. It was very welcoming.", es: "Aterricé en la ropa. Me recibió muy bien." },
    { en: "The spool rack lost its balance while I found mine.", es: "El soporte de carretes perdió el equilibrio mientras yo encontraba el mío." },
    { en: "I followed the instructions until they went underneath my belly.", es: "Seguí las instrucciones hasta que quedaron debajo de mi barriga." },
    { en: "Does this knot need all these extra knots?", es: "¿Este nudo necesita todos estos nudos adicionales?" },
    { en: "I tipped the basket back up. Its contents declined.", es: "Volví a poner la cesta derecha. Su contenido no quiso." },
    { en: "My shadow surprised me behind the sewing machine.", es: "Mi sombra me sorprendió detrás de la máquina de coser." },
    { en: "I thought the fringe was waving. I waved back too hard.", es: "Pensé que los flecos saludaban. Devolví el saludo con demasiada fuerza." },
    { en: "One sock went in. One cat came out wearing it.", es: "Entró un calcetín. Salió un gato llevándolo puesto." },
    { en: "The yarn ball took the stairs. I took a tumble.", es: "El ovillo bajó los escalones. Yo bajé dando tumbos." },
    { en: "I sorted the scraps by how far they flutter.", es: "Ordené los retazos según lo lejos que vuelan." },
    { en: "This sleeve has an exit. I chose the wrong end.", es: "Esta manga tiene una salida. Elegí el extremo equivocado." },
    { en: "I tried to peek inside and wore the paper bag.", es: "Intenté mirar dentro y terminé con la bolsa de papel puesta." },
    { en: "Something tugged my tail. Oh. My other paw.", es: "Algo tiró de mi cola. Ah. Mi otra pata." },
    { en: "I brought the small basket through the smaller gap.", es: "Metí la cesta pequeña por el hueco aún más pequeño." },
    { en: "The chalk rolled away before I finished sniffing it.", es: "La tiza se fue rodando antes de que terminara de olerla." },
    { en: "My helpful nudge has become a full yarn avalanche.", es: "Mi empujoncito de ayuda se convirtió en una avalancha de lana." },
    { en: "I am not tangled. I am several paths at once.", es: "No estoy enredado. Soy varios caminos a la vez." },
    { en: "The bow came undone when I inspected its middle.", es: "El lazo se deshizo cuando inspeccioné el centro." },
    { en: "I chased a loose thread straight into my own blanket.", es: "Perseguí un hilo suelto hasta meterme en mi propia manta." },
    { en: "Your neat row of buttons now makes a question mark.", es: "Tu fila ordenada de botones ahora forma un signo de pregunta." },
    { en: "I tried to whisper and hiccupped at the customer.", es: "Intenté susurrar y me dio hipo frente al cliente." },
    { en: "The tissue paper remembered every step of my escape.", es: "El papel de seda recordó cada paso de mi huida." },
    { en: "I lifted one ribbon and the entire bundle cheered.", es: "Levanté una cinta y todo el manojo celebró." },
    { en: "Can you tell which whisker is holding this thread?", es: "¿Puedes ver qué bigote está sujetando este hilo?" },
    { en: "I leaned on the folded fabric. It unfolded its opinion.", es: "Me apoyé en la tela doblada. Desplegó su opinión." },
    { en: "The drawer closed before my curiosity finished looking.", es: "El cajón se cerró antes de que mi curiosidad terminara de mirar." },
    { en: "I found a shortcut. It leads back into the knot.", es: "Encontré un atajo. Vuelve a llevar al nudo." },
    { en: "The gift tag says handmade. Does that include paw-made?", es: "La etiqueta dice hecho a mano. ¿Incluye hecho con patas?" },
    { en: "I bumped the chair and apologized to the table.", es: "Choqué con la silla y le pedí perdón a la mesa." },
    { en: "This ribbon trail is evidence of a very good intention.", es: "Este rastro de cintas demuestra una intención muy buena." },
    { en: "I thought we were unraveling. Apparently, we were knitting.", es: "Pensé que estábamos destejiendo. Al parecer, estábamos tejiendo." },
    { en: "My ears found the low shelf before my eyes did.", es: "Mis orejas encontraron el estante bajo antes que mis ojos." },
    { en: "The yarn slipped away while I was celebrating catching it.", es: "La lana se escapó mientras celebraba haberla atrapado." },
    { en: "I have accidentally wrapped the stool for someone.", es: "He envuelto el taburete para alguien sin querer." },
    { en: "That tiny spool makes a surprisingly large clatter.", es: "Ese carrete diminuto hace un ruido sorprendentemente grande." },
    { en: "I shook off the thread. It settled on my head.", es: "Me sacudí el hilo. Se me quedó en la cabeza." },
    { en: "The tassel and I are having trouble saying goodbye.", es: "A la borla y a mí nos cuesta despedirnos." },
    { en: "I rolled in the scraps and became a patchwork cat.", es: "Rodé entre los retazos y me convertí en un gato de parches." },
    { en: "The straight line on your pattern has acquired a paw.", es: "La línea recta de tu patrón ha adquirido una pata." },
    { en: "I tried to carry two spools. I now have none.", es: "Intenté llevar dos carretes. Ahora no tengo ninguno." },
    { en: "There was a gap between the cushions. I investigated deeply.", es: "Había un hueco entre los cojines. Lo investigué a fondo." },
    { en: "Why is the other end of this yarn also here?", es: "¿Por qué el otro extremo de esta lana también está aquí?" },
    { en: "I mistook your empty mitten for a sleeping friend.", es: "Confundí tu manopla vacía con un amigo dormido." },
    { en: "I turned around carefully. The hanging ribbons turned with me.", es: "Giré con cuidado. Las cintas colgantes giraron conmigo." },
    { en: "The paper pattern slid. I continued being surprised.", es: "El patrón de papel se deslizó. Yo seguí sorprendido." },
    { en: "I tucked the thread away and tucked myself beside it.", es: "Guardé el hilo y me guardé junto a él." },
    { en: "I was rescuing the yarn from its suspiciously round shape.", es: "Estaba rescatando la lana de su forma sospechosamente redonda." },
    { en: "The ribbon spool rolled perfectly between my waiting paws.", es: "El carrete de cinta pasó justo entre mis patas preparadas." },
    { en: "I climbed out of the basket carrying its entire lining.", es: "Salí de la cesta llevándome todo su forro." },
    { en: "This is either a lovely necklace or unfinished work.", es: "Esto es un collar precioso o un trabajo sin terminar." },
    { en: "I sneaked past the parcels with my least quiet paw.", es: "Pasé a escondidas junto a los paquetes con mi pata menos silenciosa." },
    { en: "The wool caught on my collar and requested a tour.", es: "La lana se enganchó en mi collar y pidió una visita guiada." },
    { en: "I tried holding the tissue down by jumping on it.", es: "Intenté sujetar el papel de seda saltando encima." },
    { en: "My nose pushed the pincushion. I have backed away politely.", es: "Mi nariz empujó el alfiletero. Me he apartado con educación." },
    { en: "I found the missing ribbon under the other missing ribbon.", es: "Encontré la cinta perdida debajo de la otra cinta perdida." },
    { en: "The basket lid fits like a hat with poor planning.", es: "La tapa de la cesta encaja como un sombrero mal pensado." },
    { en: "I tripped over nothing. Nothing was very sneaky.", es: "Tropecé con nada. Nada fue muy sigiloso." },
    { en: "This knot looks like my signature. I cannot write.", es: "Este nudo parece mi firma. No sé escribir." },
    { en: "I nudged the yarn toward you. It selected the doorway.", es: "Empujé la lana hacia ti. Eligió la puerta." },
    { en: "I left a paw-shaped gap in the neatly stacked scraps.", es: "Dejé un hueco con forma de pata en los retazos bien apilados." },
    { en: "The fabric tunnel collapsed into a very nice blanket.", es: "El túnel de tela se derrumbó formando una manta muy agradable." },
    { en: "I thought the spool was stuck. It was under me.", es: "Pensé que el carrete estaba atascado. Estaba debajo de mí." },
    { en: "My tail swept the labels into alphabetical confusion.", es: "Mi cola barrió las etiquetas y las dejó en confusión alfabética." },
    { en: "I got free, then stepped on the same loop.", es: "Me liberé y luego pisé el mismo bucle." },
    { en: "This gift bow has become a rather personal project.", es: "Este lazo de regalo se ha convertido en un proyecto bastante personal." },
    { en: "I sneezed while hiding. The whole workshop found me.", es: "Estornudé mientras me escondía. Todo el taller me encontró." },
    { en: "I brought you a ribbon that was attached to something.", es: "Te traje una cinta que estaba unida a algo." },
    { en: "The embroidery hoop rolled away like it had an appointment.", es: "El bastidor salió rodando como si tuviera una cita." },
    { en: "I took one tiny step and rearranged three colors.", es: "Di un pasito diminuto y reorganicé tres colores." },
    { en: "This thread keeps pulling. Perhaps we should introduce ourselves.", es: "Este hilo sigue tirando. Quizá deberíamos presentarnos." },
    { en: "I checked behind the cushion and forgot my back half.", es: "Miré detrás del cojín y olvidé mi mitad trasera." },
    { en: "The soft scraps caught me before the floor could.", es: "Los retazos suaves me atraparon antes de llegar al suelo." },
    { en: "I will help tidy up as soon as I locate myself.", es: "Ayudaré a ordenar en cuanto me encuentre a mí mismo." },
    { en: "You laughed instead of sighing. I feel less tangled already.", es: "Te reíste en vez de suspirar. Ya me siento menos enredado." },
    { en: "Could you start untangling at the end with my nose?", es: "¿Podrías empezar a desenredar por el extremo de mi nariz?" },
    { en: "I made a mess and brought my very best apology.", es: "Hice un desastre y traje mi mejor disculpa." },
  ],
};
