export const text = {
  upgradesTab: 'Upgrades', achievementsTab: 'Achievements', collectionShort: 'Cats', olympusShort: 'Olympus',
  boardEyebrow: 'THE VERY SERIOUS CAT COMMITTEE', boardTitle: 'Big ideas. Tiny handwriting.',
  boardSubtitle: 'Chapter improvements, approved by the head of naps.', boardNote: 'Please do not eat the sticky notes.',
  boardReset: 'A fresh board in every new chapter.', unlocked: 'Unlocked', locked: 'In progress',
  achievementsTitle: 'Little wins, proudly displayed.', achievementsSubtitle: 'A scrapbook of your finest pawprints. Badges stay with you through every chapter.',
  achievementCategory: 'Achievement category', allCategories: 'All achievements', achievementsCount: (n: number, total: number) => `${n} / ${total} earned`,
  achievementsUnlocked: (count: number) => `${count} achievements unlocked! See your scrapbook.`,
  achievementUnlocked: (name: string) => `Achievement unlocked: ${name}`,
  olympusTitle: 'Mount Pawlympus', olympusSubtitle: 'A tiny pantheon for your greatest little ideas. These blessings last forever.',
  divineBlessings: 'Permanent blessings', statueTitles: ['Keeper of the hearth', 'Patron of helping paws', 'Master of the golden thread'],
  crewTypes: '10 specialized cat crews', lockedTalent: 'Master Knitters blessing required',

  brand: 'Purrfect Threads', tagline: 'A little yarn. A lot of cats.', eyebrow: 'SMALL PAWS. BIG POSSIBILITIES.',
  subtitle: 'Pull a thread. Make a friend. Build something cozy.',
  workshop: 'Workshop', collection: 'Cat collection', chapter: 'New chapter', settings: 'Settings',
  yarn: 'YARN IN YOUR STASH', perSecond: 'yarn / sec', workingCats: 'working cats',
  pull: 'Pull yarn', holdHint: 'Tap the yarn, or hold to keep pulling', keyboardHint: 'You can hold Space, too',
  shopEyebrow: 'GROW YOUR LITTLE EMPIRE', shopTitle: 'More paws. More possibilities.',
  shopSubtitle: 'A happy crew makes the yarn flow.', team: 'Your crew', upgrades: 'Little improvements',
  next: 'Next on your wish list', bought: 'Purchased', maxed: 'Team complete',
  collectionEyebrow: 'THE PURRFECT COMPANY', collectionTitle: 'Meet your little legends.',
  collectionSubtitle: 'Grow your crew to meet new friends. They stay with you through every chapter.',
  select: 'Choose companion', selected: 'Your companion', preview: 'Your first friend is waiting',
  prestigeEyebrow: 'A FRESH BALL OF POSSIBILITIES', prestigeTitle: 'Every ending is a softer beginning.',
  prestigeSubtitle: 'Move to a new workshop. Bring your memories, your cats, and a little wisdom.',
  prestigeButton: 'Begin a new chapter', talents: 'A little wiser, forever', pointName: 'golden paws',
  resetTitle: 'Ready for a fresh start?', resetLose: 'Your yarn stash, working teams, buildings, and chapter upgrades reset.',
  resetKeep: 'Keep your collection, talents, golden paws, statistics, and settings. Your cats are moving with you.',
  cancel: 'Stay here', confirm: 'Move to the new workshop', close: 'Close',
  settingsTitle: 'Make yourself comfortable.', volume: 'Sound volume', reducedMotion: 'Reduced motion',
  quality: 'Visual quality', auto: 'Balanced', low: 'Battery saver', high: 'Extra fluffy',
  export: 'Export save', import: 'Import save', saveHint: 'Saved on this device. Export a backup before switching browsers.',
  saved: 'Saved with love', saving: 'Saving…', notSaved: 'Saving unavailable', saveError: 'Saving is unavailable. Export a backup to keep your progress.',
  recovered: 'Your last valid backup was recovered. Export a new backup when you can.',
  corruptTitle: 'Your save needs a little care.',
  corruptBody: 'Neither saved copy could be read. Nothing has been erased. Download the existing data before restoring a backup or starting over.',
  downloadDamaged: 'Download existing data', fresh: 'Start a new workshop', importConfirm: 'Replace this workshop with the selected save? Your current progress will be exported first.',
  invalidImport: 'That save could not be imported. Your current workshop has not changed.',
  imported: 'Your workshop is ready. Welcome back!',
  duplicateTitle: 'Your cats are busy in another tab.', duplicateBody: 'Close the other game tab, then reload this one to keep one safe copy of your progress.',
  webgl: 'The 3D workshop could not load. You can still play with the Pull yarn button. Try enabling browser graphics acceleration.',
  footer: 'Made for slow afternoons & big little dreams.',
  prototype: 'PLAYABLE PROTOTYPE · 0.2',
  adopt: (name: string) => `Adopt ${name}`,
  owned: (count: string) => `${count} owned`,
  catsAdded: (count: string) => `+${count} cats`,
  productionAdded: (count: string) => `+${count} yarn / sec`,
  cost: (count: string) => `${count} yarn`,
  unlockCats: (count: number) => `Meet at ${count.toLocaleString('en-US')} working cats`,
  chapterLabel: (count: number) => `CHAPTER ${String(count + 1).padStart(2, '0')} · THE COZY WORKSHOP`,
  reward: (count: string) => `+${count} golden paws`,
  remaining: (count: string) => `${count} more lifetime yarn to your next golden paw`,
  offline: (count: string) => `Welcome back! Your cats made ${count} yarn while you were away.`,
  milestone: (name: string) => `${name} joined your collection!`,
  crewJoined: (count: string) => `${count} new paws on the team.`,
  progressGoal: (count: string) => `${count} / 75 yarn`,
  firstGoal: 'Your first little helper', firstGoalDetail: '75 yarn brings home your first kitten.',
  nextGoal: (name: string) => `Make room for ${name}`,
  percent: (percent: number) => `${percent}% of the way there`,
  perTap: (count: string) => `+${count} per touch`,
  spendPoints: (count: number) => `${count} golden paw${count === 1 ? '' : 's'}`,
  talentBought: 'A new trick, kept forever.', upgradeBought: 'A little improvement. A lot of possibility.',
  cap: 'Prototype safety limit: 10,000 purchases per team type.',
  brandFirst: 'Purrfect', brandSecond: 'Threads', titleFirst: 'A little yarn.', titleSecond: 'A lot of cats.',
  sectionsLabel: 'Workshop sections', playAreaLabel: 'Your yarn workshop', managementLabel: 'Workshop management',
  quantityLabel: 'Purchase quantity', max: 'Max', thisChapter: 'THIS CHAPTER',
  mute: 'Mute sound', unmute: 'Unmute sound', buy: (name: string) => `Buy ${name}`,
  breakHint: 'Your cats keep working while you take a break.', chapterBrings: 'YOUR NEXT CHAPTER BRINGS',
  familyTitle: 'A family worth purring about.', familyCount: '6 / 6 friends',
  familyDetail: 'Your entire collection moves with you into every new chapter.',
  freshStart: 'A fresh start, with familiar friends.',
  browserTitle: 'A newer browser, please.',
  startError: 'The workshop could not start. Reload to try again. Saved data has not been erased.',
  browserBody: 'This workshop needs the Web Locks API to keep your save safe. Use a recent Chrome, Edge, Firefox, or Safari browser.',
};
