import { test, expect } from '@playwright/test';
import { createGame } from '../src/game/engine';
import { encode, SAVE_KEY } from '../src/game/storage';
import { enterWorkshop } from './entry';

test('only opening each unlocked patch clears its unread status, including after reload', async ({ page }) => {
  const game = createGame(Date.now());
  game.stats.taps = 75;
  game.achievements = ['first-thread', 'persistent-paws'];
  await page.addInitScript(({key, raw}) => {
    if (!localStorage.getItem(key)) localStorage.setItem(key, raw);
  }, {key: SAVE_KEY, raw: encode(game)});
  await page.goto('/'); await enterWorkshop(page);
  const nav = page.locator('.navigation [data-screen="achievements"]');
  const count = page.locator('#achievement-unread-count');
  await expect(count).toHaveText('2');
  await expect(count).toHaveCSS('position', 'relative');
  await expect(count).toHaveCSS('background-image', /data:image\/svg\+xml/);
  await expect(nav.locator(':scope > .icon')).toBeHidden();
  const number = await count.boundingBox();
  const button = await nav.boundingBox();
  expect(number!.x).toBeGreaterThanOrEqual(button!.x);
  expect(number!.y).toBeGreaterThanOrEqual(button!.y);
  expect(number!.y + number!.height).toBeLessThanOrEqual(button!.y + button!.height);
  await nav.click();
  await expect(count).toHaveText('2');
  await expect(page.locator('#achievement-first-thread')).toHaveClass(/unread/);
  await expect(page.locator('#achievement-persistent-paws')).toHaveClass(/unread/);
  await expect(page.locator('#achievement-paw-marathon')).not.toHaveClass(/unread/);
  await page.locator('#achievement-paw-marathon').click();
  await expect(count).toHaveText('2');
  await page.keyboard.press('Escape');
  await page.locator('#achievement-first-thread').click();
  await expect(page.locator('.achievement-story')).not.toBeEmpty();
  await expect(count).toHaveText('1');
  await expect(page.locator('#achievement-first-thread')).not.toHaveClass(/unread/);
  await expect(page.locator('#achievement-persistent-paws')).toHaveClass(/unread/);
  await page.keyboard.press('Escape');
  await page.locator('#achievement-first-thread').click();
  await expect(count).toHaveText('1');
  await page.reload(); await enterWorkshop(page);
  await expect(count).toHaveText('1');
  await nav.click();
  await expect(page.locator('#achievement-persistent-paws')).toHaveClass(/unread/);
  await page.locator('#achievement-persistent-paws').click();
  await expect(count).toBeHidden();
  await expect(nav.locator(':scope > .icon')).toBeVisible();
});
